### PR TITLE
Add gem `rubocop-thread_safety`

### PR DESCRIPTION
**Pull request by nimmolo**
Before we turn on threading in Puma, which can run multiple threads, we need to be pretty confident our code is thread safe. An example of the danger is that a global like `User.current` is changed by a different thread, and CRUD actions are "randomly" misattributed to the wrong user.

This PR attempts to help us [check for potential thread safety problems](https://github.com/rubocop/rubocop-thread_safety#correcting-code-for-thread-safety) in our code by adding the gem `rubocop-thread_safety`. 

Note that there are no hard and fast rules, this stuff is contextual and requires a firmer grasp of how the code is executed than I have.

To get a standalone report, after installing the gem, run this command locally:
```
rubocop -r rubocop-thread_safety --only ThreadSafety,Style/GlobalVars,Style/ClassVars,Style/MutableConstant
```
Report updated by Joe below.

### CODE REVIEW

**Comment by nimmolo** [comment]
@mo-nathan if you know anything about safer workarounds for either of these usages that are flagged by the gem, suggestions welcome. Our violations (which may or may not potentially cause problems in production with Puma, I don't know) boil down to two types:
- "mutating class and module attributes"
- "instance variables in class methods"

**Comment by JoeCohen** [comment]
@nimmolo You've probably already seen this, but just in case: [Correcting code for thread-safety
](https://www.rubydoc.info/gems/rubocop-thread_safety/0.4.2#correcting-code-for-thread-safety)

**Comment by JoeCohen** [comment]
>Here's the report I got on our current codebase on main. Not bad:

Unfortunately, it's somewhat worse. Running
```sh
rubocop -r rubocop-thread_safety --only ThreadSafety,Style/GlobalVars,Style/ClassVars,Style/MutableConstant
```
uses the configuration of `.rubocop.yml`, which in turn inherits from `.rubocop_todo.yml`, (see https://docs.rubocop.org/rubocop/configuration.html#automatically-generated-configuration), which Exclude's many offenses from the report.  
The report at the top has about 25 offenses.
The actual number is
```ruby
1087 files inspected, 95 offenses detected
```

Here's what I'll do now to get an accurate count of threading issue in this branch (and on main) and to have the `rubocop` command above work properly for present purposes.

- [ ] Create a new branch
  - [ ] Update rubocop (which may fix some false positives or negatives for threading issues)
  - [ ] Regenerate the `.rubocop_todo.yml`
  - [ ]  Edit `.rubocop_todo.yml` to remove exclusions of thread-related cops
- [ ] Create a PR. **WARNING** There will be at least 70 new Codeclimate offenses (because editing `.rubocop_todo.yml` unveils some offense which that file hides)
- [ ] Merge the new branch into `main`, ignoring the Codeclimate warning.
- [ ] Merge `main` into this branch (`nimmo-thread-safety`) so that:
  - This branch includes @pellaea's recent fixes of of thread issues; 
  - `.rubocop_todo.yml` no longer hides threading offenses
  - `rubocop -r rubocop-thread_safety --only ThreadSafety,Style/GlobalVars,Style/ClassVars,Style/MutableConstant` works OK for present purposes.
- [ ] Regenerate the threading offenses report and paste it into this branch.

**Comment by JoeCohen** [comment]
### RuboCop Inspection Report

Updated 2023-02-21 11:54 PSR
1088 files inspected, 87 offenses detected:

#### app/classes/content_filter.rb - (1 offense)
  - [ ] **Line # 45 - convention:** Style/ClassVars: Replace class var @@filters with a class instance var.

    ```rb
        @@filters ||= [
    ```

#### app/classes/ip_stats.rb - (4 offenses)
  - [ ] **Line # 141 - convention:** Style/ClassVars: Replace class var @@blocked_ips_time with a class instance var.

    ```rb
          @@blocked_ips_time = nil
    ```

  - [ ] **Line # 168 - convention:** Style/ClassVars: Replace class var @@blocked_ips with a class instance var.

    ```rb
          @@blocked_ips = parse_ip_list(file1)
    ```

  - [ ] **Line # 169 - convention:** Style/ClassVars: Replace class var @@okay_ips with a class instance var.

    ```rb
          @@okay_ips = parse_ip_list(file2)
    ```

  - [ ] **Line # 170 - convention:** Style/ClassVars: Replace class var @@blocked_ips_time with a class instance var.

    ```rb
          @@blocked_ips_time = [File.mtime(file1), File.mtime(file2)].max
    ```

#### app/classes/robots.rb - (3 offenses)
  - [ ] **Line # 13 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          populate_allowed_robot_actions unless defined?(@allowed_robot_actions)
    ```

  - [ ] **Line # 16 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          @allowed_robot_actions["#{args[:controller]}/#{args[:action]}"]
    ```

  - [ ] **Line # 21 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          @allowed_robot_actions = parse_robots_dot_text(file)
    ```

#### app/classes/run_level.rb - (3 offenses)
  - [ ] **Line # 6 - convention:** Style/ClassVars: Replace class var @@runlevel with a class instance var.

    ```rb
      @@runlevel = :normal
    ```

  - [ ] **Line # 9 - convention:** Style/ClassVars: Replace class var @@runlevel with a class instance var.

    ```rb
        @@runlevel = :normal
    ```

  - [ ] **Line # 13 - convention:** Style/ClassVars: Replace class var @@runlevel with a class instance var.

    ```rb
        @@runlevel = :silent
    ```

#### app/classes/textile.rb - (20 offenses)
  - [ ] **Line # 32 - convention:** Style/ClassVars: Replace class var @@name_lookup with a class instance var.

    ```rb
      @@name_lookup     = {}
    ```

  - [ ] **Line # 33 - convention:** Style/ClassVars: Replace class var @@last_species with a class instance var.

    ```rb
      @@last_species    = nil
    ```

  - [ ] **Line # 34 - convention:** Style/ClassVars: Replace class var @@last_subspecies with a class instance var.

    ```rb
      @@last_subspecies = nil
    ```

  - [ ] **Line # 35 - convention:** Style/ClassVars: Replace class var @@last_variety with a class instance var.

    ```rb
      @@last_variety    = nil
    ```

  - [ ] **Line # 151 - convention:** Style/ClassVars: Replace class var @@name_lookup with a class instance var.

    ```rb
        @@name_lookup ||= {}
    ```

  - [ ] **Line # 155 - convention:** Style/ClassVars: Replace class var @@last_species with a class instance var.

    ```rb
          @@last_species    = name
    ```

  - [ ] **Line # 156 - convention:** Style/ClassVars: Replace class var @@last_subspecies with a class instance var.

    ```rb
          @@last_subspecies = nil
    ```

  - [ ] **Line # 157 - convention:** Style/ClassVars: Replace class var @@last_variety with a class instance var.

    ```rb
          @@last_variety    = nil
    ```

  - [ ] **Line # 159 - convention:** Style/ClassVars: Replace class var @@last_species with a class instance var.

    ```rb
          @@last_species    = name.sub(/ ssp\. .*/, "")
    ```

  - [ ] **Line # 160 - convention:** Style/ClassVars: Replace class var @@last_subspecies with a class instance var.

    ```rb
          @@last_subspecies = name
    ```

  - [ ] **Line # 161 - convention:** Style/ClassVars: Replace class var @@last_variety with a class instance var.

    ```rb
          @@last_variety    = nil
    ```

  - [ ] **Line # 163 - convention:** Style/ClassVars: Replace class var @@last_species with a class instance var.

    ```rb
          @@last_species    = name.sub(/ (ssp|var)\. .*/, "")
    ```

  - [ ] **Line # 164 - convention:** Style/ClassVars: Replace class var @@last_subspecies with a class instance var.

    ```rb
          @@last_subspecies = name.sub(/ var\. .*/, "")
    ```

  - [ ] **Line # 165 - convention:** Style/ClassVars: Replace class var @@last_variety with a class instance var.

    ```rb
          @@last_variety    = name
    ```

  - [ ] **Line # 188 - convention:** Style/ClassVars: Replace class var @@name_lookup with a class instance var.

    ```rb
        @@name_lookup ||= {}
    ```

  - [ ] **Line # 194 - convention:** Style/ClassVars: Replace class var @@name_lookup with a class instance var.

    ```rb
        @@name_lookup     = {}
    ```

  - [ ] **Line # 195 - convention:** Style/ClassVars: Replace class var @@last_species with a class instance var.

    ```rb
        @@last_species    = nil
    ```

  - [ ] **Line # 196 - convention:** Style/ClassVars: Replace class var @@last_subspecies with a class instance var.

    ```rb
        @@last_subspecies = nil
    ```

  - [ ] **Line # 197 - convention:** Style/ClassVars: Replace class var @@last_variety with a class instance var.

    ```rb
        @@last_variety    = nil
    ```

  - [ ] **Line # 252 - convention:** Style/ClassVars: Replace class var @@name_lookup with a class instance var.

    ```rb
        @@name_lookup ||= {}
    ```

#### app/classes/token.rb - (1 offense)
  - [ ] **Line # 24 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
        @crypt ||= ActiveSupport::MessageEncryptor.new(
    ```

#### app/controllers/application_controller.rb - (2 offenses)
  - [ ] **Line # 1323 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          @index_subaction_param_keys ||= []
    ```

  - [ ] **Line # 1327 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          @index_subaction_dispatch_table ||= {}
    ```

#### app/extensions/symbol_extensions.rb - (4 offenses)
  - [ ] **Line # 22 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
        @raise_errors = turn_on
    ```

  - [ ] **Line # 26 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
        @raise_errors
    ```

  - [ ] **Line # 45 - convention:** Style/ClassVars: Replace class var @@missing_tags with a class instance var.

    ```rb
        @@missing_tags = [] unless defined?(@@missing_tags)
    ```

  - [ ] **Line # 51 - convention:** Style/ClassVars: Replace class var @@missing_tags with a class instance var.

    ```rb
        @@missing_tags = tags
    ```

#### app/models/abstract_model.rb - (1 offense)
  - [ ] **Line # 641 - convention:** ThreadSafety/ClassAndModuleAttributes: Avoid mutating class and module attributes.

    ```rb
      class_attribute :autolog_events
    ```

#### app/models/language.rb - (1 offense)
  - [ ] **Line # 126 - convention:** Style/ClassVars: Replace class var @@last_update with a class instance var.

    ```rb
      @@last_update = 1.minute.ago
    ```

#### app/models/language_exporter.rb - (4 offenses)
  - [ ] **Line # 40 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          @locales_path = "config/locales" if @locales_path.nil?
    ```

  - [ ] **Line # 40 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          @locales_path = "config/locales" if @locales_path.nil?
    ```

  - [ ] **Line # 41 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          "#{::Rails.root}/#{@locales_path}"
    ```

  - [ ] **Line # 45 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
          @locales_path = path
    ```

#### app/models/language_tracking.rb - (5 offenses)
  - [ ] **Line # 35 - convention:** Style/ClassVars: Replace class var @@tags_used with a class instance var.

    ```rb
      @@tags_used = nil
    ```

  - [ ] **Line # 36 - convention:** Style/ClassVars: Replace class var @@last_clean with a class instance var.

    ```rb
      @@last_clean = nil
    ```

  - [ ] **Line # 43 - convention:** Style/ClassVars: Replace class var @@tags_used with a class instance var.

    ```rb
        @@tags_used = {}
    ```

  - [ ] **Line # 52 - convention:** Style/ClassVars: Replace class var @@tags_used with a class instance var.

    ```rb
        @@tags_used = nil
    ```

  - [ ] **Line # 105 - convention:** Style/ClassVars: Replace class var @@last_clean with a class instance var.

    ```rb
        @@last_clean = Time.zone.now
    ```

#### app/models/location.rb - (3 offenses)
  - [ ] **Line # 320 - convention:** Style/ClassVars: Replace class var @@names_for_unknown with a class instance var.

    ```rb
        @@names_for_unknown ||= official_unknown
    ```

  - [ ] **Line # 526 - convention:** Style/ClassVars: Replace class var @@location_cache with a class instance var.

    ```rb
      @@location_cache = nil
    ```

  - [ ] **Line # 533 - convention:** Style/ClassVars: Replace class var @@location_cache with a class instance var.

    ```rb
        @@location_cache ||= (
    ```

#### app/models/query_record.rb - (3 offenses)
  - [ ] **Line # 34 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
        return unless !defined?(@last_cleanup) ||
    ```

  - [ ] **Line # 35 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
                      (@last_cleanup < 5.minutes.ago) ||
    ```

  - [ ] **Line # 40 - convention:** ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.

    ```rb
        @last_cleanup = Time.zone.now
    ```

#### app/models/queued_email.rb - (2 offenses)
  - [ ] **Line # 144 - convention:** Style/ClassVars: Replace class var @@all_flavors with a class instance var.

    ```rb
          @@all_flavors = []
    ```

  - [ ] **Line # 161 - convention:** ThreadSafety/ClassAndModuleAttributes: Avoid mutating class and module attributes.

    ```rb
      cattr_accessor(:queue, default: false)
    ```

#### app/models/user.rb - (6 offenses)
  - [ ] **Line # 376 - convention:** Style/ClassVars: Replace class var @@user with a class instance var.

    ```rb
        @@user = nil unless defined?(@@user)
    ```

  - [ ] **Line # 385 - convention:** Style/ClassVars: Replace class var @@user with a class instance var.

    ```rb
        @@user = nil unless defined?(@@user)
    ```

  - [ ] **Line # 392 - convention:** Style/ClassVars: Replace class var @@location_format with a class instance var.

    ```rb
        @@location_format = val ? val.location_format : "postal"
    ```

  - [ ] **Line # 393 - convention:** Style/ClassVars: Replace class var @@user with a class instance var.

    ```rb
        @@user = val
    ```

  - [ ] **Line # 401 - convention:** Style/ClassVars: Replace class var @@location_format with a class instance var.

    ```rb
        @@location_format = "postal" unless defined?(@@location_format)
    ```

  - [ ] **Line # 407 - convention:** Style/ClassVars: Replace class var @@location_format with a class instance var.

    ```rb
        @@location_format = val
    ```

#### app/models/user_group.rb - (6 offenses)
  - [ ] **Line # 88 - convention:** Style/ClassVars: Replace class var @@all_users with a class instance var.

    ```rb
        @@all_users ||= get_or_construct_user("all users")
    ```

  - [ ] **Line # 94 - convention:** Style/ClassVars: Replace class var @@one_users with a class instance var.

    ```rb
        @@one_users ||= {}
    ```

  - [ ] **Line # 100 - convention:** Style/ClassVars: Replace class var @@reviewers with a class instance var.

    ```rb
        @@reviewers ||= get_or_construct_user("reviewers")
    ```

  - [ ] **Line # 106 - convention:** Style/ClassVars: Replace class var @@all_users with a class instance var.

    ```rb
        @@all_users = @@one_users = @@reviewers = nil
    ```

  - [ ] **Line # 106 - convention:** Style/ClassVars: Replace class var @@one_users with a class instance var.

    ```rb
        @@all_users = @@one_users = @@reviewers = nil
    ```

  - [ ] **Line # 106 - convention:** Style/ClassVars: Replace class var @@reviewers with a class instance var.

    ```rb
        @@all_users = @@one_users = @@reviewers = nil
    ```

#### test/controllers/locations_controller_test.rb - (4 offenses)
  - [ ] **Line # 9 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails ||= []
    ```

  - [ ] **Line # 18 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails = []
    ```

  - [ ] **Line # 25 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails = []
    ```

  - [ ] **Line # 33 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails = []
    ```

#### test/controllers/names_controller_test.rb - (4 offenses)
  - [ ] **Line # 11 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails ||= []
    ```

  - [ ] **Line # 20 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails = []
    ```

  - [ ] **Line # 27 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails = []
    ```

  - [ ] **Line # 35 - convention:** Style/ClassVars: Replace class var @@emails with a class instance var.

    ```rb
        @@emails = []
    ```

#### test/general_extensions.rb - (1 offense)
  - [ ] **Line # 289 - convention:** Style/ClassVars: Replace class var @@fixture_labels with a class instance var.

    ```rb
      @@fixture_labels = {}
    ```

#### test/language_extensions.rb - (7 offenses)
  - [ ] **Line # 10 - convention:** Style/ClassVars: Replace class var @@verbose_messages with a class instance var.

    ```rb
      @@verbose_messages = []
    ```

  - [ ] **Line # 13 - convention:** Style/ClassVars: Replace class var @@localization_files with a class instance var.

    ```rb
        @@localization_files = {}
    ```

  - [ ] **Line # 14 - convention:** Style/ClassVars: Replace class var @@export_files with a class instance var.

    ```rb
        @@export_files = {}
    ```

  - [ ] **Line # 18 - convention:** Style/ClassVars: Replace class var @@localization_files with a class instance var.

    ```rb
        @@localization_files = nil
    ```

  - [ ] **Line # 19 - convention:** Style/ClassVars: Replace class var @@export_files with a class instance var.

    ```rb
        @@export_files = nil
    ```

  - [ ] **Line # 23 - convention:** Style/ClassVars: Replace class var @@last_update with a class instance var.

    ```rb
        @@last_update = val
    ```

  - [ ] **Line # 27 - convention:** Style/ClassVars: Replace class var @@verbose_messages with a class instance var.

    ```rb
        @@verbose_messages = []
    ```

#### test/test_helper.rb - (2 offenses)
  - [ ] **Line # 153 - convention:** Style/ClassVars: Replace class var @@times with a class instance var.

    ```rb
          @@times = {} unless defined?(@@times)
    ```

  - [ ] **Line # 173 - convention:** Style/ClassVars: Replace class var @@cleared_logs with a class instance var.

    ```rb
          @@cleared_logs = true
    ```

**Comment by JoeCohen** [comment]
1. Yes it should include everything current, except the ones Jason fixed. 
It's just the current output of the RuboCop command that you started with, output in `.md` format (and I tweaked the format a bit to use checkboxes.) You can read more about the format options at https://docs.rubocop.org/rubocop/formatters.html.

Although class instance variables are better than class variables, they still may be problematic for thread safety. See https://bearmetal.eu/theden/how-do-i-know-whether-my-rails-app-is-thread-safe-or-not/.

**Comment by nimmolo** [comment]
@JoeCohen - did you notice that it's flagging your `@index_subaction` ivars in `app/controllers/application_controller.rb`? How should we handle that?

Or... are these OK because they're only ever instantiated in a controller that inherits from this, and controller ivars are thread safe by definition. Or... is it very much the opposite, and the ivar "belongs" to ApplicationController and is getting mutated unpredictably?

**Comment by JoeCohen** [comment]
@nimmolo I hadn't noticed that. I will have to think it over.
Perhaps @mo-nathan has some thoughts; he pointed the way to this refactor.
Another issue may be that these ivars use the non-atomic operator `||=`. See [here](https://bearmetal.eu/theden/how-do-i-know-whether-my-rails-app-is-thread-safe-or-not/), particularly
> Don’t memoize to class variables or class instance variables. If you need to memoize something on the class level, use thread local variables (Thread.current[:baz]) instead. Be aware, though, that it is still kind of a global variable. So while it’s thread-safe, it still might not be good coding practice.

**Comment by nimmolo** [comment]
Should we merge this so we can use it while working on thread safety?

**Pull request merged**
