### PR TITLE
AccountControllerTest#test_blocked_ips — Tried setting file times more explicitly so that this test works

### PR DESCRIPTION
**Pull request by pellaea**
on all systems.

### CODE REVIEW

**Comment by nimmolo** [comment]
The rubocop `Do not use to_time on Date objects, because they know nothing about the time zone in use.` is a false positive and has been corrected in recent rubocop, according to this issue thread:
https://github.com/rubocop/rubocop-rails/issues/288

**Comment by nimmolo** [comment]
This fixes it for me. THANK YOU @pellaea !

**Comment by nimmolo** [comment]
Added a tweak to match expectation format of calls to get(action, **args) 

`get(:blocked_ips, params: { add_bad: new_ip })`
`get(:blocked_ips, params: { remove_bad: new_ip })`

**Comment by nimmolo** [comment]
Codeclimate checks should clear if #960 merges first (see note above)

**Comment by JoeCohen** [comment]
Jason: Thanks for fixing this. Works like a charm. I was getting so tired
of seeing that test fail.
As Nimmo suggested, Codeclimate is happy with
AccountControllerTest#test_blocked_ips...#962 now that #960 is merged.
I will merge it.

**Pull request merged**
