### PR TITLE
[Delivers ##163505539] Change numerical comparisons to predicates

### PR DESCRIPTION
**Pull request by JoeCohen**
Predicates are the RuboCop default style and preferred by the MO developers. See https://mushroomobserver.slack.com/archives/C040TH9FV/p1548618290041400
- Delete configuration which used non-default style
- Change all instances of numerical comparisons to numerical predicates
- Exclude one non-Ruby file from Rubocop

### CODE REVIEW

**Comment by JoeCohen** [comment]
Coverage decrease https://coveralls.io/builds/21312089 is bogus. 
All the alleged "New Missed Lines" are lines with changes (e.g. from `== 0` to `zero?`, which lines were previously missed. Coveralls can't tell the difference between a new line and a changed line.

**Comment by JoeCohen** [comment]
May I remove `AbstractModel#find_version`? 
It's not tested and I can't find any calls at all to that method.

**Comment by mo-nathan** [comment]
I suspect the coveralls change is really because of some of the changes going from one line to multiple lines and them not being covered.  That probably triggers with warning and then they mark all the new/changed lines that aren't being covered.

**Comment by mo-nathan** [comment]
Note: I removed a few rubocop:disable/rubocop:enable pairs that are no longer needed.  Rubocop once again only reports Metrics issues.

**Pull request merged**
