### PR TITLE
config/environment/test.rb - add config.action_view.cache_template_loading = true

### PR DESCRIPTION
**Pull request by nimmolo**
Seems desirable, in that it may speed up controller or integration tests. 
It's a new Rails 6 config, what do you guys think?

### CODE REVIEW

**Comment by pellaea** [comment]
Why not?  Do we understand how it actually works, though?  I'm concerned that it either won't help at all unless we do something else, or it will attempt to cache things that aren't actually static.

**Comment by nimmolo** [comment]
Will research it and report back.

**Comment by nimmolo** [comment]
> `config.action_view.cache_template_loading` controls whether or not templates should be reloaded on each request. Defaults to whatever is set for config.cache_classes.

Sounds like it is both pretty harmless and won't alter anything, actually, because if the above is true, it already defaults to true in our case. But IIRc, last night I needed it to get the 6.1 branch happy. For that reason I vote to add the config.

**Comment by nimmolo** [comment]
Further research: This config [goes all the way back to Rails 3.1](https://guides.rubyonrails.org/v3.1/configuring.html), and has always defaulted to `true` if `config.cache_classes` was true. So I think we're good.

**Comment by nimmolo** [comment]
Aha, I think I get what was going on, and why it occurred to me to add it. 
What's "new" in Rails 6 is that the `rails update` task now adds this particular config explicitly to `config/environments/test.rb` by default. I presume that's to fix whatever error I was experiencing in tests.

**Comment by pellaea** [comment]
Cool, thanks for looking into it, Nimmo.

**Pull request merged**
