### PR TITLE
Add assertions to test_observations_of_name

### PR DESCRIPTION
**Pull request by JoeCohen**
Adds some assertions to ObservationsControllerTest#test_observations_of_name

### CODE REVIEW

**Comment by JoeCohen** [comment]
This was the first step in something I've now put on hold. I thought it was worth merging independently.
(What I put on hold was: Add a `Review` link to the Observation index template. Clicking that link would create a new query and display its results -- Observations in set, where the members of the set are the result of the old query. I thought this would be a quick and dirty way to address Alan's need for a better way to ID unknowns. But it seems that Alan would like something more ambitious, and @nimmolo is in the mood to tackle it.)

**Review by pellaea — APPROVED** [review]
Useful test.  Your idea of turning a query into an "in_set" query to fix the order is clever!

**Review by nimmolo — APPROVED** [review]
I also like that `in_set` idea...

**Comment by JoeCohen** [comment]
Thank you @pellaea & @nimmolo for the feedback. Maybe I'll take that Idea up next week.

**Pull request merged**
