### PR TITLE
`ApplicationHelper` - use `AbstractModel.controller_normalized?` for next/prev links

### PR DESCRIPTION
**Pull request by nimmolo**
I'd defined a constant in `ApplicationHelper`, `REFACTORED_CONTROLLERS_WITH_FLOW`, to define which controllers can use the next/prev `flow` param, without realizing @JoeCohen  already had made the convenient method `controller_normalized?` in `AbstractModel`. 

This PR (on the refactor ObserverController branch) switches the link helper to use that method on the object, instead of us having to maintain an array of refactored controllers.

### CODE REVIEW

**Comment by pellaea** [comment]
I was confused about that.  Yes, I also prefer Joe's controller_normalized? method, and I like maintaining it individually in the classes that are normalized as opposed to having to remember to add it to a global array.

I'm not sure what being "assigned" to this PR means.  Is that another version of "review requested"?

**Comment by JoeCohen** [comment]
@nimmolo: I will look at the Codeclimate issues, starting from the bottom up at https://codeclimate.com/github/MushroomObserver/mushroom-observer/pull/1058.
And I will push them in groups >= 1.

**Comment by JoeCohen** [comment]
Amendment: 
Working bottom-up, if I hit an offense that's auto-correctable, I'll correct all offenses of that type.

**Comment by JoeCohen** [comment]
It will take a while, and I may not finish. (But I'll fix at least some of them.)
So if you want to merge before I finish, just do it.

**Comment by nimmolo** [comment]
I'm thinking to simplify `controller_normalized?` a bit more, removing the arg. Let me know what you guys think.

**Comment by nimmolo** [comment]
@pellaea User error on the part of your "assigner" ! Meant to request review.

**Comment by JoeCohen** [comment]
Sorry. I'm trying a different procedure:
- From bottom up
- Files_with_offenses.each do |file|
  - auto-correctable_offenses.each {  |offense| auto-correct or disable for all files }
  - non-autocorrectable_offenses.each { |offense| auto-correct or disable for this file }

I have to go away for a while. 30 minutes?

**Comment by JoeCohen** [comment]
@nimmolo Rubocop likes a newline at the end of files.
If you like, VsCode will do that automatically. https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files

**Comment by nimmolo** [comment]
Thanks Joe - I modified the settings to auto-add the newline. (Been trying to catch them manually, but alas.)

As i'm attempting to "normalize" ObservationsController in a separate PR, i'm finding a lot of uses for `controller_normalized?`

**Comment by JoeCohen** [comment]
Now really away for ~60-90 minutes. Will resume after dinner.

**Comment by JoeCohen** [comment]
The failure is not in the test suite, but in the attempt to run Coveralls. 
```
Run coverallsapp/github-action@master
Using lcov file: ./coverage/lcov/lcov.info
Error: Bad response: 405
405 Not Allowed
nginx
```
I don't have time to look into this today.

**Comment by JoeCohen** [comment]
I'm done with my attempts to fix the new Codeclimate issues listed in https://codeclimate.com/github/MushroomObserver/mushroom-observer/pull/1058#
- I fixed the non-Metric ones
- I did not attempt to fix the Metric ones (ABC, too many lines in a method, module, or class). That would take too long.

**Comment by nimmolo** [comment]
Thanks for all this, Joe. Glad you got it in.

**Pull request merged**
