### PR TITLE
Merge master into nimmo-graphql-experiments branch

### PR DESCRIPTION
**Pull request by nimmolo**
This PR is mostly so i can figure out what all i've changed on the branch `nimmo-graphql-experiments`, and keep the branch up to date with master

### CODE REVIEW

**Comment by nimmolo** [comment]
Ah - this needs to wait until the other two are merged.

**Comment by pellaea** [comment]
Should I go ahead and merge them and push them out now?  I'm stretched very
thin and have only a dim grasp of which PRs are ready to be merged.  So
just tell me what to do and I'll do it!

**Comment by nimmolo** [comment]
No thanks! 
Well actually, i believe the credentials one should be mergeable without any further ado, but I want to write the test for the new `rss_log.detail` the way you laid out. Just making a note to myself there. 

I started trying to merge master into this branch and realized there were conflicts that were about to be resolved. Didn't want to command-line-resolve the same conflicts twice.

**Comment by pellaea** [comment]
Okay, I'll do the credentials now.

**Comment by pellaea** [comment]
Sorry, I can't.  Github isn't working for me right now.  But I was able to
get as far as seeing that all this PR does is add a single file -- the
encrypted credentials file.  Fair enough!  That could scarcely be more
innocuous. :)  So I'll merge that as soon as I get github to work for me
again.

**Comment by JoeCohen** [comment]
I'll do it.

**Comment by JoeCohen** [comment]
Done.

**Comment by nimmolo** [comment]
Thanks Joe!

**Pull request merged**
