### PR TITLE
drag and drop

### PR DESCRIPTION
**Pull request by raysuelzer**
Users can now drag and drop anywhere on the page.  This builds upon the EXIF pull request.

### CODE REVIEW

**Comment by raysuelzer** [comment]
This includes #177

**Comment by pellaea** [comment]
Thanks, Ray.  I'm going to leave these for the moment, because I expect
Nathan will want to do a more critical review than I'm willing or able to
do.  (I shouldn't have bothered with the lightbox branch on origin -- it's
so easy to pull your branch directly and test it as is before merging the
PR.)

**Comment by raysuelzer** [comment]
All good.

**Comment by mo-nathan** [comment]
Apparently I can't push my conflict fix to this branch, so I created a new pull.  Don't know if that's the right approach or not.  In any case I've not been able to get this functionality to work locally.  I'll followup with details on the mo-dev mailing list.

**Pull request merged**
