### PR TITLE
JS-ify `collection_number` form actions on observation page

### PR DESCRIPTION
**Pull request by nimmolo**
This adds on-page editing UI for links to Add, Edit, or Remove a collection number from an observation.
It also refactors the naming and comment form modals so partials are more reusable.

### CODE REVIEW

**Comment by nimmolo** [comment]
Newly untested lines are JS renders

**Comment by nimmolo** [comment]
@JoeCohen Would you be willing to test this manually? 
It shouldn't take more than a few minutes.

- Adding editing and removing CN's from an obs
- Be sure naming and voting still work!

**Comment by JoeCohen** [comment]
I'll give it a spin.
What are "CN's"?

**Comment by nimmolo** [comment]
Thank you! CollectionNumbersOn May 4, 2023, at 4:54 PM, Joseph D. Cohen ***@***.***> wrote:﻿
I'll give it a spin.
What are "CN's"?

**Comment by JoeCohen** [comment]
Thanks. DOH! I should have looked at the PR.
I'll try it as soon as I can get VSCode to sync with the remote.

**Comment by nimmolo** [comment]
Thanks for trying it out. I'll check into why it's a different color like that and try to get it looking the same. I may try changing a lot of those links to icons with hover "tooltip" captions in the bs4 branch, so this arrangement may be brief.On May 4, 2023, at 5:30 PM, Joseph D. Cohen ***@***.***> wrote:﻿
I did a quick test. It functions fine.
Maybe style the Remove CN button in the same color as the Edit link. Not a big deal.

**Pull request merged**
