### PR TITLE
Fix ip stats

### PR DESCRIPTION
**Pull request by pellaea**
Just rubocop stuff.

### CODE REVIEW

**Comment by JoeCohen** [comment]
Thanks for fixing this up.
Re Commit #77f3667
<https://github.com/MushroomObserver/mushroom-observer/pull/914/commits/77f366719fc486eb17e6d05bf25c96390bca0697#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR371>
 ("Not wure why this changed for me.")
Probably when you re-installed the VM, it installed the latest version of
`bundle`.
(We might have to update `bundle` on the production server when we deploy
this PR.)

**Comment by pellaea** [comment]
I did, in fact, do a "bundle install" on the production server when I
deployed it.

I wonder: could we be in some screwy state where we are using different
bundlers and Gemfile.lock is going to get subtly tweaked each time a new
developer merges a PR?

**Comment by JoeCohen** [comment]
Good question.
But maybe not a real problem. I think a machine will complain if `bundle
install` plus the various gems are being used with an incompatible version
of `bundler`.
I've seen that before but don't remember the exact circumstances. I think
it was (a) deploying something to production and seeing a complaint on the
production server, and/or (b) pulling master to my vm and running
bundle install..
Note that `bundle install` does not update bundler -- the version on the
production server is still 2.3.5

***@***.***:~$ cd /var/web/mo; sudo su mo

***@***.***:/var/web/mo$ bundler --version

Bundler version 2.3.5
I'm not sure what to do about it, and don't have time to think it through
this week.
At some point, the various machines should complain about having the wrong
version of `bundler` installed, and will suggest an update.

**Comment by pellaea** [comment]
Sounds good to me, thanks, Joe!

**Pull request merged**
