### PR TITLE
Ruby 3.3.6 and Rails 7.1.5.1

### PR DESCRIPTION
**Pull request by mo-nathan**

### CODE REVIEW

**Review by JoeCohen — COMMENTED** [review]
This runs fine (other than the iNat problem, which I 90% believe is unrelated to this PR).
@nimmolo The Ruby upgrade may break RubyLSP in VSCode. But that's not a blocker for me.

**Review by JoeCohen — APPROVED** [review]
Runs fine.
iNat issue was a false alarm, unrelated to this PR.
VSCode stuff is an non-breaking inconvenience.

**Comment by nimmolo** [comment]
Note: this branch seems to have the `csv` gem, which `main` lacks

**Comment by mo-nathan** [comment]
I just see an upgrade from csv 3.3.0 to csv 3.3.2 in Gemfile.lock.  I also see csv 3.3.0 in deploy-2024-11-07-21-22, so it's been there for a while.

**Comment by mo-nathan** [comment]
Looks like csv was removed very recently from Gemfile.lock on main as part of @JoeCohen removing httparty today.  Merging in main and running `bundle update` caused it to be remove from the Gemfile.lock.

**Review by nimmolo — APPROVED** [review]
Works for me.

**Comment by nimmolo** [comment]
Thanks for doing all this.

**Pull request merged**
