### PR TITLE
Fixed few bugs in multi image uploader.

### PR DESCRIPTION
**Pull request by pellaea**

### CODE REVIEW

**Comment by raysuelzer** [comment]
Thank you!

On Saturday, January 31, 2015, Jason Hollinger <notifications@github.com>
wrote:

> Merged #49 <https://github.com/MushroomObserver/mushroom-observer/pull/49>
> .
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/MushroomObserver/mushroom-observer/pull/49#event-228066749>
> .
>


-- 
Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
Arg, just noticed another minor bug... How did we miss all these things?!
It's not giving me the right default license.  I should be
wikipedia-compatible, and just verified my prefs and bulk-updated my last
several images to make sure.  But sure enough, it's still trying to make
then non-commercial.  Wonder if it's just an index being off by one or
something...

**Comment by raysuelzer** [comment]
It should be set by rails in the multi image template.

It's the drop down that is being set wrong or it's being saved wrong?

On Saturday, January 31, 2015, Jason Hollinger <notifications@github.com>
wrote:

> Arg, just noticed another minor bug... How did we miss all these things?!
> It's not giving me the right default license. I should be
> wikipedia-compatible, and just verified my prefs and bulk-updated my last
> several images to make sure. But sure enough, it's still trying to make
> then non-commercial. Wonder if it's just an index being off by one or
> something...
>
> On Sat, Jan 31, 2015 at 4:47 PM, Raymond Suelzer <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Thank you!
> >
> > On Saturday, January 31, 2015, Jason Hollinger <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Merged #49 <
> > https://github.com/MushroomObserver/mushroom-observer/pull/49>
> > > .
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/MushroomObserver/mushroom-observer/pull/49#event-228066749
> > >
> > > .
> > >
> >
> >
> > --
> > Ray Suelzer
> > Mobile: (312) 869-2665
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345194>
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345280>
> .
>


-- 
Ray Suelzer
Mobile: (312) 869-2665

**Comment by raysuelzer** [comment]
Yes very simple bug. I'm not setting default license in that template.  Ugh
so sorry. That was my first stab at this app.



On Saturday, January 31, 2015, Raymond Suelzer <rsuelzer@gmail.com> wrote:

> It should be set by rails in the multi image template.
>
> It's the drop down that is being set wrong or it's being saved wrong?
>
> On Saturday, January 31, 2015, Jason Hollinger <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Arg, just noticed another minor bug... How did we miss all these things?!
>> It's not giving me the right default license. I should be
>> wikipedia-compatible, and just verified my prefs and bulk-updated my last
>> several images to make sure. But sure enough, it's still trying to make
>> then non-commercial. Wonder if it's just an index being off by one or
>> something...
>>
>> On Sat, Jan 31, 2015 at 4:47 PM, Raymond Suelzer <
>> notifications@github.com>
>> wrote:
>>
>> > Thank you!
>> >
>> > On Saturday, January 31, 2015, Jason Hollinger <
>> notifications@github.com>
>> > wrote:
>> >
>> > > Merged #49 <
>> > https://github.com/MushroomObserver/mushroom-observer/pull/49>
>> > > .
>> > >
>> > > --
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/MushroomObserver/mushroom-observer/pull/49#event-228066749
>> > >
>> > > .
>> > >
>> >
>> >
>> > --
>> > Ray Suelzer
>> > Mobile: (312) 869-2665
>> >
>> > --
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345194>
>>
>> > .
>> >
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345280>
>> .
>>
>
>
> --
> Ray Suelzer
> Mobile: (312) 869-2665
>
>

-- 
Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
Yeah, got it, testing now.

**Comment by raysuelzer** [comment]
I'm sure I missed this because on my dev instance there are no default
licenses. The stripped snapshot will be VERY helpful.

On Saturday, January 31, 2015, Jason Hollinger <notifications@github.com>
wrote:

> Yeah, got it, testing now.
>
> On Sat, Jan 31, 2015 at 5:11 PM, Raymond Suelzer <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Yes very simple bug. I'm not setting default license in that template.
> Ugh
> > so sorry. That was my first stab at this app.
> >
> >
> >
> > On Saturday, January 31, 2015, Raymond Suelzer <rsuelzer@gmail.com
> <javascript:_e(%7B%7D,'cvml','rsuelzer@gmail.com');>> wrote:
> >
> > > It should be set by rails in the multi image template.
> > >
> > > It's the drop down that is being set wrong or it's being saved wrong?
> > >
> > > On Saturday, January 31, 2015, Jason Hollinger <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > >
> > >> Arg, just noticed another minor bug... How did we miss all these
> > things?!
> > >> It's not giving me the right default license. I should be
> > >> wikipedia-compatible, and just verified my prefs and bulk-updated my
> > last
> > >> several images to make sure. But sure enough, it's still trying to
> make
> > >> then non-commercial. Wonder if it's just an index being off by one or
> > >> something...
> > >>
> > >> On Sat, Jan 31, 2015 at 4:47 PM, Raymond Suelzer <
> > >> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > >> wrote:
> > >>
> > >> > Thank you!
> > >> >
> > >> > On Saturday, January 31, 2015, Jason Hollinger <
> > >> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > >> > wrote:
> > >> >
> > >> > > Merged #49 <
> > >> > https://github.com/MushroomObserver/mushroom-observer/pull/49>
> > >> > > .
> > >> > >
> > >> > > --
> > >> > > Reply to this email directly or view it on GitHub
> > >> > > <
> > >> >
> > >>
> >
> https://github.com/MushroomObserver/mushroom-observer/pull/49#event-228066749
> > >> > >
> > >> > > .
> > >> > >
> > >> >
> > >> >
> > >> > --
> > >> > Ray Suelzer
> > >> > Mobile: (312) 869-2665
> > >> >
> > >> > --
> > >> > Reply to this email directly or view it on GitHub
> > >> > <
> > >>
> >
> https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345194
> > >
> > >>
> > >> > .
> > >> >
> > >>
> > >> --
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345280
> > >
> > >> .
> > >>
> > >
> > >
> > > --
> > > Ray Suelzer
> > > Mobile: (312) 869-2665
> > >
> > >
> >
> > --
> > Ray Suelzer
> > Mobile: (312) 869-2665
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345839>
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/MushroomObserver/mushroom-observer/pull/49#issuecomment-72345906>
> .
>


-- 
Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
Yeah, sorry about that, should've given you that ages ago.  These days I
rely on unit tests way too heavily, forgotten how to test things the
old-fashioned way.  It'll be so nice when you get selenium working, hint
hint. ;)

**Pull request merged**
