### PR TITLE
Refactor `MOMultiImageUploader` without jQuery

### PR DESCRIPTION
**Pull request by nimmolo**
Same functionality, just no jQuery. Uses JS Fetch API, compatible with Stimulus. Preparation for Rails 7.

#### One new thing I thought would be nice: ####
- when you upload images, the window smoothly scrolls to the images.

## Manual Test ##

Please test manually. Create an obs with images, and give all the image upload features a workout: date sync, set as thumbnail, etc.

### CODE REVIEW

**Comment by JoeCohen** [comment]
It's not working for me. 
- Create Observation; 
- drag an image to the MO page; 
Result: the page doesn't change. It should display the image, include any options to change the image/obs date & location, etc.

**Comment by nimmolo** [comment]
Thanks @JoeCohen. Sheesh, I've been using the `Select Images` button the whole time! 
(Despite rewriting the handlers for drag and drop!)

**Comment by nimmolo** [comment]
@JoeCohen Just fixed the image drop zone. Should work now.

**Review by JoeCohen — APPROVED** [review]
I did some quick manual tests and it works fine.
Thanks for the cleanup.

**Pull request merged**
