### PR TITLE
Don't enforce imageless.

### PR DESCRIPTION
**Pull request by orbea**
This just opens the door for 1000s of other names for `Imageless` and will get really silly fast.

A better solution will be to be to address issue https://github.com/MushroomObserver/mushroom-observer/issues/222. 

As for observations with a herbarium specimen, if a specimen exists than an image of the dried specimen should also be possible. If its not then that is enough reason to suspect the specimen either does not exist or has been lost.

### CODE REVIEW

**Comment by orbea** [comment]
Here is a prime example of why these commits were a bad idea.

http://mushroomobserver.org/246992?q=2oKv8

Part of a species list so that "Imageless" can not be posted, but without any images or even name...
http://mushroomobserver.org/246992?q=2oKv8

**Comment by pellaea** [comment]
This is not the place for debate about MO policy.  In fact I'm a little
tired of getting of hearing nothing but complaints from users who do
nothing to contribute to the development or running of MO.  Please send the
webmasters / admins your comments.  When I'm done with my field season I
promise I'll read them.  Meanwhile it pollutes the one channel of email
that in principle I should be trying to keep up with in my few precious
spare moments.

Besides, the debate about imageless observations was closed years ago.
Nathan made his position crystal clear.  At this point we're just playing a
stupid game with a troll who was walking the line between annoyance and
vandalism.  Thanks to this commit, the troll was forced to cross that line
and can now be removed from the site without any concerns of it being
called censorship.  We've given him his last warning.  As far as I'm
concerned it's over and I will remove all this silliness in a few months
once everything calms down again.  And I have the time to play games again.

Now I'm deleting this "pull request" and hopefully won't have to play
*this* game again, either.

**Comment by orbea** [comment]
Another example...this qualifies under both your rules 3 & 4....

http://mushroomobserver.org/50248?q=2oKv8

**Comment by pellaea** [comment]
Look, they aren't my damned rules.  You accomplish nothing by pestering me
with this issue.  I'm going out of town now, and I hope to hell I don't
have a mountain of Imageless BS in my inbox when I get back.

**Pull request closed without merging**
