### PR TITLE
bootstrap4 HerbariaController

### PR DESCRIPTION
**Pull request by JoeCohen**
Turn HerbariaControllerTest green (when the PR is ready for review).

### CODE REVIEW

**Comment by JoeCohen** [comment]
All tests green. Now fo some refactoring.

**Comment by JoeCohen** [comment]
I'm making this "ready for review" because all tests are green and I've done the easy refactoring.

I should spend lots more time on it, but don't want to do so now. I created [Pivotal Story #173480416](https://www.pivotaltracker.com/story/show/173480416) covering these issues:
- Overall design: :show can be called with either GET or POST. The POST stuff should be moved, maybe to its own action `:add_curator`. Or maybe all the curator modification stuff should be part of `:edit`/`:update`
- Class Size. Maybe divide into (a) actions that just display stuff; (b) CRUD actions.
- Other metrics violations: ABC, perceived complexity, method size

I'm also surprised that `post :show` works. I don't see a corresponding route in the output of `rails route`. But note:
>"By default, Rails creates routes for the seven default actions (index, show, new, create, edit, update, and destroy) for every RESTful route in your application." https://guides.rubyonrails.org/routing.html#restricting-the-routes-created

**Comment by JoeCohen** [comment]
Oh no! Travis pr build aborts. I need to look into this, so turning it back to a Draft PR.

**Comment by JoeCohen** [comment]
Travis was fixed, thanks to @mo-nathan!

**Comment by nimmolo** [comment]
This is fantastic, Joe.

**Comment by JoeCohen** [comment]
Thanks. I'll merge it.
I'd like to get the pending PR's merged in order to minimize conflicts. (Conflicts with others people's branches are inevitable and reasonable, but conflicts with my own stuff is wasteful and annoying.)

**Pull request merged**
