### PR TITLE
Add ml flag

### PR DESCRIPTION
**Pull request by mo-nathan**
To test:

1. Go to a show image page
2. See the "Okay for Machine Learning | Not for Machine Learning" UI elements
3. Ensure that they work and are persistent

### CODE REVIEW

**Review by JoeCohen — APPROVED** [review]

**Comment by JoeCohen** [comment]
Oops: I accidentally deleted my comment that said:
>I think you should merge and deploy this.
It looks great, and points the way to a more generalized way to tag stuff with values.
For me it's always an education to see how you do things,
though I'm afraid I don't retain much.

**Review by pellaea — APPROVED** [review]
This looks good except for what looks like two typos in the update_snapshots script.

**Comment by JoeCohen** [comment]
Nathan has already merged and deployed it.
Would it be possible for you to fix the typos and re-deploy?

**Comment by mo-nathan** [comment]
I’ll fix up update_snapshots and actually test it this. 🤠

**Comment by pellaea** [comment]
Thanks!  I almost missed it, too. :)

**Comment by JoeCohen** [comment]
Nathan:
Thanks for doing this.
I'll look at the PR in a few minutes.
- Joe

**Pull request merged**
