### PR TITLE
Fix add deprecated names

### PR DESCRIPTION
**Pull request by JoeCohen**
See discussion at https://groups.google.com/forum/#!topic/mo-developers/cSzyESoeTk0
fixes 3 test Failures in species_controller_test
Now at:
  1160 tests, 16471 assertions, 4 failures, 0 errors, 1 skips

### CODE REVIEW

**Comment by pellaea** [comment]
Oops!  I think you meant to request pull into ror4 not master! :)

**Comment by pellaea** [comment]
Looks like only one commit at the end, I can cherry-pick that commit if
you'd like.

**Comment by JoeCohen** [comment]
Yes thats what meant.  Thanks for catchting it.  I made a pull request to
the right place.  Am now going offline until tomorrow a.m.

**Comment by JoeCohen** [comment]
Accidentally made this PR to pull into master instead of ror4.  Correct request has been made.

**Pull request closed without merging**
