### PR TITLE
Bump gem versions for three recent Dependabot security updates

### PR DESCRIPTION
**Pull request by nimmolo**
For some reason the dependabot PRs don't pass tests, they lack the Rails credentials. 
This PR does the same updates "manually": #1216 #1234 & #1235.

Gems updated: `nokogiri 1.13.10`, `loofah 2.19.1`, `rails-html-sanitizer 1.4.4`

### CODE REVIEW

**Comment by nimmolo** [comment]
The difference between this PR and the dependabot version is that I spec'd a minimum nokogiri version in the Gemfile.

Does anyone know a reason not to put nokogiri in the Gemfile?

**Comment by JoeCohen** [comment]
Makes sense.(The only thing I can think of is the future theoretical
possibility that Nokogiri get abandoned by all the gems that we use, so we
no longer need it, so we shouldn't install it. That's pretty far-fetched.)

**Comment by nimmolo** [comment]
Thanks @JoeCohen . Merging now

**Comment by nimmolo** [comment]
Updated to add two new Dependabot suggestions.

**Pull request merged**
