### PR TITLE
Remove interview-code remnants

### PR DESCRIPTION
**Pull request by JoeCohen**
This PR removes (dead) remnants of code that facilitated Gianna Nguyen's interviews about user experience.
Most of that code had already been removed, but the following still lingered:
- a route (removed in this PR);
- a reference to the route (removed in this PR)
- a view (removed in this PR);
- a reference to the interview in the banner (which this PR brings up-to-date).

### CODE REVIEW

**Comment by pellaea** [comment]
Thanks, Joe!  Great to clean up these old things.

**Comment by JoeCohen** [comment]
Thanks Jason. I just converted this to a draft because there's something screwed up in my repo or Git Gui. 
I will reopen it when it's ready for merger.

**Comment by JoeCohen** [comment]
Ready for merger.

My motive for doing this now: 
I finally started work on blocking unregistered users from most pages. 
I ran across a reference to the :interview route in ObserverController.  I want to delete it so there's one tiny fewer thing to deal with. And while I'm at it, complete the cleanup.

**Comment by pellaea** [comment]
I'll look at it soon as I can get github to show it to me! :)

**Comment by pellaea** [comment]
Seems straightforward enough.  Okay by me to merge this.

**Pull request merged**
