### PR TITLE
Rubocop 1.30

### PR DESCRIPTION
**Pull request by JoeCohen**
This PR updates RuboCop and associated gems and files.  The purpose is to have the latest RuboCop bug fixes (as well as new cops).
The PR updates:
- `rubocop`, `rubocop_performance`, and `rubocop_rails` gems to the latest versions, removing the now-useless `mry` gem;
- Codeclimate configuration to use a newer version of RuboCop;
- RuboCop configuration to disable new cops by default, simplify directions for updating RuboCop;
- RuboCop todo file (unfortunately adding hundreds of new offenses).

There is no manual test.

### CODE REVIEW

**Comment by JoeCohen** [comment]
1. As a test, I merged (locally) this branch into Fix Rails/HttpPositionalArguments offenses #957, ran 
```
rubocop -f html -o rubocop.html --only Rails/HttpPositionalArguments
```
and got zero offenses. So I think this branch indeed fixes the HttpPositionalArguments false positives.
2. I'll get to work on the CodeClimate issues in a few minutes.

**Comment by pellaea** [comment]
I think the has_many missing inverse_of offences are pretty
straightforward: just add "inverse_of :target" to all the has_many
:comments and has_many :interests relationships throughout the code.  Why
it doesn't infer that the "inverse_of" option is identical to the "as"
option, I don't know.  But it's easy enough to be explicit.

**Comment by JoeCohen** [comment]
Thanks Jason.
But now there are conflicts with master (in Gemfile.lock). I should fix them before dealing with Codeclimate. They should be easy.
But taking a break now.

**Comment by pellaea** [comment]
How do you mean?  I show that production has a modified version of
db/schema.rb, but that Gemfile.lock is in sync with master.

**Comment by nimmolo** [comment]
@JoeCohen This looks great, and i'm glad it clears up those HttpPositionalArguments offenses.
Shall I knock out those two codeclimate issues?

**Comment by JoeCohen** [comment]
Thanks @nimmolo. I'll take care of the CodeClimate stuff now. (I got diverted by some website issues.)

**Comment by JoeCohen** [comment]
I will merge this. 
GitHub says "codeclimate — 3 issues to fix". 
But when I click the Details link, it says "All good!No new issues were found."
I think the 3 issues are Fixme (a Codeclimate plugin) issues which I've told Codeclimate that I won't fix.

**Pull request merged**
