### PR TITLE
Start to refactor Query flavors

### PR DESCRIPTION
**Pull request by nimmolo**
Starts to move all Query flavors into `:all` using expanded params, to facilitate the storing of queries as a simple hash of params. Addresses #2425. 

This PR does the easier ones.

### CODE REVIEW

**Comment by nimmolo** [comment]
@JoeCohen I'm noticing that `SequencesController#index` does not handle pattern searches, or index params via the dispatcher in `ApplicationController` like other indexes. This means that pattern searches for sequences will not work, `param[:pattern]` is ignored by the index.

I assume there's a reason for that, but I wanted to check with you in case that's unintentional.

**Comment by nimmolo** [comment]
Oh - we don't offer Sequence pattern search. Interesting that the query can handle the pattern param.

**Comment by JoeCohen** [comment]
It simply hadn't occurred to me to offer Sequence pattern search.
It's a poor way to search for DNA patterns. Might be useful for text or other parts of an MO Sequence.
IMO low priority.

**Comment by nimmolo** [comment]
This is ready to go, but i can hold until after NEMF if people prefer.

I did this refactor according to @pellaea's advice, and Query is pretty well tested, but I don't want to be the one messing up NEMF.

**Pull request merged**
