### PR TITLE
Fix "name lister" js

### PR DESCRIPTION
**Pull request by nimmolo**
Hopefully restores original functionality!
#1897

### CODE REVIEW

**Comment by nimmolo** [comment]
@mo-nathan If you get a chance, please give this a spin and let me know if it behaves correctly.

**Comment by mo-nathan** [comment]
Seems better after merging in the latest changes on main and running the usual update stuff.  However, the names are weird.  They appear to be coming from the test fixtures for some reason rather than mo_development as I would expect.  It's possible it's coming from mo_test which gets loaded with the test fixture, but I dropped that database and the weird names continue to show up.  It also doesn't make sense to me why the middle panel lists all the species for the genera that have been selected so far.

**Comment by nimmolo** [comment]
- Weird names: On dev, these come from a static file Jason created long ago to test the name lister — they aren't intended to be up to date. On production, the names are generated via a nightly script from the live db.
- I'll ask Jason, but I think it always listed the species names of all selected Genera in the middle panel.

**Comment by mo-nathan** [comment]
Interesting.  I'm guessing this is coming from test/reports/name_list_data.js.  At this point I don't like the behavior in the center panel, but at least it seems to work reasonably.

**Review by mo-nathan — APPROVED** [review]

**Comment by nimmolo** [comment]
Oh. Maybe i get it - you're expecting the middle column to ONLY show species of the _currently selected_ Genus...

That was confusing me. Just changed it, this should do it.

**Comment by mo-nathan** [comment]
Yes, that's exactly what I meant.  Awesome!  Thanks for fixing this.

**Pull request merged**
