### PR TITLE
Bootstrap 4, controllers & views refactor

### PR DESCRIPTION
**Pull request by nimmolo**
This draft PR is not yet ready for review... just sharing it for reference to the ongoing work!

Outline of work: 
Refactor ObserverController into constituent controllers
Migrate some methods, actions and templates from "older-style controller/action/id arguments" to "newer RESTful routes" for legibility and future code maintainability (albeit a lot of grunt work now)
Refactor Views to use Bootstrap 4 layout components and JS, including lightbox, popup, etc.
Refactor the Search Bar to show variations relevant to the current View context
Audit query loads and query caching potential in all views to reduce render times
Audit content delivery for bandwidth hogs and potential streamlining

### CODE REVIEW

**Comment by JoeCohen** [comment]
@nimmolo: 
1. How can the rest of us help? (I'm happy to do non-js and non-css grunt work. I'm completely ignorant of js and don't want to touch the css because it's so closely tied to the js.)
2. Would it make sense to have this in a branch (something like "Bootstrap-4-Plus" rather than master?
3. Would it make sense for you to pull and resolve conflicts (but not CodeClimate issues) the latest changes to master? That might make it easier work on other things, but would slow you down.
4. Question: Are you working MO Developer VM machine?

**Comment by pellaea** [comment]
Holy moly, you aren't kidding, Nimmo.  Thanks for this *huge* amount of
work.  I need to understand better what these audits mean.  If anyone can
pull off the magic of improving query times, I'm sure it's you.

@Joseph Cohen <jdcohenesq@gmail.com>: Would making this a branch make it
easier to collaborate on this?  I can also imagine making PRs to Nimmo's
clone of master on his repo would work, and he'd keep ownership that way.
But I've never collaborated on something this big before, so I don't know
the pros and cons of the various approaches.

**Comment by JoeCohen** [comment]
I don't know about working on a branch vs on @nimmolo's master. I'm ignorant about the plusses and minuses; I asked about a branch because that's what I've done here.
If control is an issue, could we work off a branch (or branch of a branch) in @nimmolo's repo
Maybe @mo-nathan can give us some guidance. 
Also Martin Fowler's blog has a brand-new series, [Patterns for Managing Source Code Branches](https://martinfowler.com/articles/branching-patterns.html). Now I'll have to actually read it. :-)
PS `@joseph` is someone else. But maybe we can recruit him. :-)

**Comment by JoeCohen** [comment]
1. I looked at the Fowler blog. It (so far) doesn't answer my question -- whether it's better to work: 
- directly on a copy of the master branch of the MO repo (what Fowler calls Mainline Integration);
- directly on a copy of a feature branch of the MO repo (this is what we did for ruby-2.6.6); or
- copy the MO master branch, then create a feature branch in one developer's repo (Fowler's Feature Branching). (Fowler does note that "Feature Branching is a popular pattern in the industry today." He also says that its principal alternative is Continuous Integration, which will be a future blog episode.)

2. My uneducated 2¢is that it would be clearer to work on a branch with a different name. 
If @nimmolo wants to retain control (makes sense to me), that would be a branch in his repo. If others wanted to work on it, they would make PRs to that branch of his repo.

3. Fowler emphasizes the importance of integrating frequently. https://martinfowler.com/articles/branching-patterns.html#IntegrationFrequency. It doesn't answer my question, but seems a lot more important.

**Comment by nimmolo** [comment]
@joe I like the idea of working off a feature branch.

I will move these changes to a new branch of my repo later today, using the name you proposed. I’ll also try to resolve any new diffs with the MO master.

To your question about helping, I feel like the refactor phase i'm in right now will be tricky to collaborate on without screwing something up, or investing a lot of time getting on the same page, but i will definitely want more eyes on it when it gets closer, particularly in making sure the tests fit the new refactor.




On 28 Apr 2020, at 13:39, Joseph D. Cohen <notifications@github.com> wrote:

﻿
I looked at the Fowler blog. It (so far) doesn't answer my question -- whether it's better to work:
directly on a copy of the master branch of the MO repo (what Fowler calls Mainline Integration);
directly on a copy of a feature branch of the MO repo (this is what we did for ruby-2.6.6); or
copy the MO master branch, then create a feature branch in one developer's repo (Fowler's Feature Branching). (Fowler does note that "Feature Branching is a popular pattern in the industry today." He also says that its principal alternative is Continuous Integration, which will be a future blog episode.)
My uneducated 2¢is that it would be clearer to work on a branch with a different name.
If @nimmolo wants to retain control (makes sense to me), that would be a branch in his repo. If others wanted to work on it, they would make PRs to that branch of his repo.

Fowler emphasizes the importance of integrating frequently. https://martinfowler.com/articles/branching-patterns.html#IntegrationFrequency. It doesn't answer my question, but seems a lot more important.

**Comment by pellaea** [comment]
Sounds good to me -- feature branch on Nimmo's repo.  I still haven't found
a spare minute even to glance at your work, Nimmo, sorry!  Not likely to
happen tonight either, I'm beat.   But big yes on helping to test and such
when you have things roughed in.  That's a great way for us to learn how
things have changed and get used to the new look and feel.  Maybe it will
rain for a week some day soon. ;)
-Jason

**Comment by JoeCohen** [comment]
1. I took a tiny, quick peek at the files. While changing some things to the Rails Way might not be required (e.g., pluralizing controller names), I like it. In general I like it for the reasons given by @nimmolo, and because I'm self-educated, part time, and an amateur: it's easier for me to understand and modify the code.
2. @nimmolo: Would it be at all helpful if I did a PR (to merge into your branch) for the changes to the MO master branch since you last pulled that branch?

**Comment by nimmolo** [comment]
@Joe 
1. Good to hear that, I hope it ends up being helpful. There's a long way to go yet...

2. … partly because i just shot myself in the foot. Tried to bring uncommitted changes, including untracked files and renamed directories, to the new branch, and they vanished. 

I hope I’ll figure it out, but i’m a bit frozen at the moment, it’s unnerving to see 2-3 days work seem to disappear.

So, i’d say please hold off on the PR for a bit, although it does seem like a great idea. Actually i wish i’d thought of it too, it might have saved me this snafu !





On April 29, 2020 at 4:04:02 PM, Joseph D. Cohen (notifications@github.com) wrote:

I took a tiny, quick peek at the files. While changing some things to the Rails Way might not be required (e.g., pluralizing controller names), I like it. In general I like it for the reasons given by @nimmolo, and because I'm self-educated, part time, and an amateur: it's easier for me to understand and modify the code.
@nimmolo: Would it be at all helpful if I did a PR (to merge into your branch) for the changes to the MO master branch since you last pulled that branch?

**Comment by JoeCohen** [comment]
Sorry to hear about the snafu.
I'll wait to hear from you before moving on my PR proposal.
Please let us know if there's anything we can do to help.

> @joe  1. Good to hear that, I hope it ends up being helpful. There's a long way to go yet... 2. … partly because i just shot myself in the foot. Tried to bring uncommitted changes, including untracked files and renamed directories, to the new branch, and they vanished.  I hope I’ll figure it out, but i’m a bit frozen at the moment, it’s unnerving to see 2-3 days work seem to disappear. So, i’d say please hold off on the PR for a bit, although it does seem like a great idea. Actually i wish i’d thought of it too, it might have saved me this snafu ! On April 29, 2020 at 4:04:02 PM, Joseph D. Cohen (notifications@github.com) wrote: I took a tiny, quick peek at the files. While changing some things to the Rails Way might not be required (e.g., pluralizing controller names), I like it. In general I like it for the reasons given by @nimmolo, and because I'm self-educated, part time, and an amateur: it's easier for me to understand and modify the code. @nimmolo: Would it be at all helpful if I did a PR (to merge into your branch) for the changes to the MO master branch since you last pulled that branch? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pellaea** [comment]
Oh man, have you not found the stashed files yet???  We all make mistakes
on git ... but you win the award for the most painful one. :(

**Comment by JoeCohen** [comment]
Glad to see you're unstuck. 
If there's a way to parcel out the CodeClimate issues (e.g., by file) I'd be happy to help.

**Comment by nimmolo** [comment]
Hi Joe-
Thanks, it's good to be unstuck! 

I'm still in the midst of applying these shortened REST method names consistently everywhere (and figuring out which ones work), it may take awhile. But i will definitely be glad for help with CodeClimate and many other issues when it’s in better shape.

By the way, do you get the full CodeClimate report? I tried to access it but i don’t have the right permissions. 

If you are able to forward it to me it would be good just to know what it’s watching out for. I’m touching tons of files and if i can tidy as i go it will make everything easier in the end.

Nimmo



On 5 May 2020, at 06:32, Joseph D. Cohen <notifications@github.com> wrote:

﻿
Glad to see you're unstuck.
If there's a way to parcel out the CodeClimate issues (e.g., by file) I'd be happy to help.

**Comment by JoeCohen** [comment]
@nimmolo: I do get the full report.
I will check later how to get it to you. Our free CodeClimate account has a very limited number of seats. Maybe I can switch out someone who is inactive and add you.

**Comment by nimmolo** [comment]
Codeclimate, although it is full of questionable advice, says:

The GitHub PR integration appears to be using an old installation and might not work as expected. Re-install it now.

Ideas? Codeclimate currently seems to be flagging code that is straight out of the most recent Rails manual, so i wonder if it could use the update.


On April 28, 2020 at 3:27:16 PM, a n (andrnimm@fastmail.fm) wrote:

@joe I like the idea of working off a feature branch.

I will move these changes to a new branch of my repo later today, using the name you proposed. I’ll also try to resolve any new diffs with the MO master.

To your question about helping, I feel like the refactor phase i'm in right now will be tricky to collaborate on without screwing something up, or investing a lot of time getting on the same page, but i will definitely want more eyes on it when it gets closer, particularly in making sure the tests fit the new refactor.




On 28 Apr 2020, at 13:39, Joseph D. Cohen <notifications@github.com> wrote:

﻿
I looked at the Fowler blog. It (so far) doesn't answer my question -- whether it's better to work:
directly on a copy of the master branch of the MO repo (what Fowler calls Mainline Integration);
directly on a copy of a feature branch of the MO repo (this is what we did for ruby-2.6.6); or
copy the MO master branch, then create a feature branch in one developer's repo (Fowler's Feature Branching). (Fowler does note that "Feature Branching is a popular pattern in the industry today." He also says that its principal alternative is Continuous Integration, which will be a future blog episode.)
My uneducated 2¢is that it would be clearer to work on a branch with a different name.
If @nimmolo wants to retain control (makes sense to me), that would be a branch in his repo. If others wanted to work on it, they would make PRs to that branch of his repo.

Fowler emphasizes the importance of integrating frequently. https://martinfowler.com/articles/branching-patterns.html#IntegrationFrequency. It doesn't answer my question, but seems a lot more important.

**Comment by JoeCohen** [comment]
> Codeclimate, although it is full of questionable advice, says: The GitHub PR integration appears to be using an old installation and might not work as expected. Re-install it now. Ideas? Codeclimate currently seems to be flagging code that is straight out of the most recent Rails manual, so i wonder if it could use the update.

**Pull request closed without merging**
