### PR TITLE
Upgrade to Ruby 3.0.4

### PR DESCRIPTION
**Pull request by nimmolo**

### CODE REVIEW

**Comment by nimmolo** [comment]
The test errors relate to the new freeze assumptions in Ruby 3.0.
ERROR AmateurTest#test_language_tracking FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"ένα", :unknown_locations=>"Unknown, Earth, World, Worldwi
test/integration/amateur_test.rb:293:in `test_language_tracking'

ERROR HerbariumRecordTest#test_personal_herbarium_name_and_languages (80.25s)
2022-05-30T23:02:48.9878327Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"une", :unknown_locations=>"Unknown, Earth, World, Worldwide, Anywhere, Everywhere", :app_banner_box=>"**Please do not re-click a li
test/models/herbarium_record_test.rb:16:in `test_personal_herbarium_name_and_languages'

ERROR LocationTest#test_unknown2 (87.20s)
2022-05-30T23:02:55.9414671Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:
test/models/location_test.rb:382:in `test_unknown2'

ERROR ObserverControllerTest#test_change_banner (143.71s)
2022-05-30T23:03:52.4531193Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"one", :unknown_locations=>"Unknown, Earth, World, World
2022-05-30T23:03:52.5025740Z             app/models/translation_string.rb:78:in `update_localization'
2022-05-30T23:03:52.5026151Z             test/controllers/observer_controller_test.rb:3698:in `block in test_change_banner'
2022-05-30T23:03:52.5026533Z             app/models/language_exporter.rb:53:in `alt_locales_path'
2022-05-30T23:03:52.5026865Z             test/general_extensions.rb:86:in `use_test_locales'
2022-05-30T23:03:52.5027210Z             test/controllers/observer_controller_test.rb:3688:in `test_change_banner'

ERROR PatternSearchTest#test_translated_parameter_names (144.58s)
2022-05-30T23:03:53.3224054Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"une", :unknown_locations=>"Unknown, Earth, World, Worldwide, Anywhere, Everywhere", :app_banner_box=>"**Please do not re-click a link while waiting for 
2022-05-30T23:03:53.3749667Z             test/models/pattern_search_test.rb:409:in `test_translated_parameter_names'
2022-05-30T23:03:53.3749958Z 
2022-05-30T23:04:26.4773186Z =========grep: /home/runner/work/mushroom-observer/mushroom-observer/log/test.log: No such file or directory
2022-05-30T23:04:26.5245893Z /home/runner/work/mushroom-observer/mushroom-observer/script/monitor_top: 15: Syntax error: "(" unexpected
2022-05-30T23:04:26.5491125Z [0m[1000D[K FAIL ScriptTest#test_monitor_top (177.89s)
2022-05-30T23:04:26.5492214Z         Something went wrong with /home/runner/work/mushroom-observer/mushroom-observer/script/monitor_top:
2022-05-30T23:04:26.5493299Z         test/models/script_test.rb:96:in `block in <class:ScriptTest>'

ERROR LanguageTest#test_update_localization (187.11s)
2022-05-30T23:04:35.8500543Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"one", :unknown_locations=>"Unknown, Earth, World, Worldwide, Anywhere, Everywhere", :app_banner_box=>"**Please do not re-click a link while waitin
2022-05-30T23:04:35.8994497Z             app/models/translation_string.rb:78:in `update_localization'
2022-05-30T23:04:35.8994888Z             test/models/language_test.rb:42:in `block in test_update_localization'
2022-05-30T23:04:35.8995248Z             app/models/language_exporter.rb:53:in `alt_locales_path'
2022-05-30T23:04:35.8995576Z             test/general_extensions.rb:86:in `use_test_locales'
2022-05-30T23:04:35.8996117Z             test/models/language_test.rb:36:in `test_update_localization'

ERROR LanguageTest#test_update_recent_translations (187.19s)
2022-05-30T23:04:35.9870205Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"one", :unknown_locations=>"Unknown, Earth, World, Worldwide, Anywhere, Everywhere", :app_banner_box=>"**Please do not re-click a link while waitin
2022-05-30T23:04:36.0386284Z             app/models/language.rb:137:in `block in update_recent_translations'
2022-05-30T23:04:36.0386973Z             app/models/language.rb:136:in `each'
2022-05-30T23:04:36.0387335Z             app/models/language.rb:136:in `update_recent_translations'
2022-05-30T23:04:36.0387720Z             test/models/language_test.rb:98:in `test_update_recent_translations'

ERROR TranslationControllerTest#test_edit_translation_form_post_save_greek (215.27s)
2022-05-30T23:05:04.0134375Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"ένα", :unknown_locations=>"Unknown, Earth, World, Worldwide, Anywhere, Everywhere", :app_banner_box=>"**Please do not re-click a link while waiti
2022-05-30T23:05:04.4892392Z         test/controllers/translation_controller_test.rb:286:in `block in test_edit_translation_ajax_form'
2022-05-30T23:05:04.4892865Z         app/models/language_exporter.rb:53:in `alt_locales_path'
2022-05-30T23:05:04.4893245Z         test/general_extensions.rb:86:in `use_test_locales'
2022-05-30T23:05:04.4893676Z         test/controllers/translation_controller_test.rb:261:in `test_edit_translation_ajax_form'

ERROR TranslationControllerTest#test_edit_translation_form_post_save_z (216.07s)
2022-05-30T23:05:04.8163515Z Minitest::UnexpectedError:         FrozenError: can't modify frozen Hash: {:all=>"all", :title_for_user_search=>"User Search", :one=>"one", :unknown_locatio
2022-05-30T23:05:04.8677741Z             app/models/translation_string.rb:78:in `update_localization'
2022-05-30T23:05:04.8678196Z             app/controllers/translation_controller.rb:148:in `change_translation'
2022-05-30T23:05:04.8678644Z             app/controllers/translation_controller.rb:122:in `block in update_translations'
2022-05-30T23:05:04.8679063Z             app/controllers/translation_controller.rb:108:in `each'
2022-05-30T23:05:04.8679471Z             app/controllers/translation_controller.rb:108:in `update_translations'
2022-05-30T23:05:04.8679898Z             app/controllers/translation_controller.rb:19:in `edit_translations'
2022-05-30T23:05:04.8680329Z             app/controllers/application_controller.rb:237:in `catch_errors_and_log_request_stats'
2022-05-30T23:05:04.8680750Z             test/functional_test_case.rb:27:in `post'
2022-05-30T23:05:04.8681136Z             test/controllers/translation_controller_test.rb:196:in `translation_for_one'
2022-05-30T23:05:04.8681604Z             test/controllers/translation_controller_test.rb:206:in `block in test_edit_translation_form_post_save_z'
2022-05-30T23:05:04.8682053Z             app/models/language_exporter.rb:53:in `alt_locales_path'
2022-05-30T23:05:04.8682422Z             test/general_extensions.rb:86:in `use_test_locales'
2022-05-30T23:05:04.8682849Z             test/controllers/translation_controller_test.rb:203:in `test_edit_translation_form_post_save_z'

ERROR NameControllerTest#test_eol (55.48s)
2022-05-30T23:02:24.1360800Z Minitest::UnexpectedError:         RuntimeError: The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives.
2022-05-30T23:02:24.1361469Z             app/classes/eol_data.rb:204:in `get_sorted_names'

NameControllerTest#test_eol_expanded_review
EolDataTest#test_glossary_term_query
EolDataTest#test_refresh_links_to_eol
EolDataTest#test_create

**Comment by nimmolo** [comment]
@pellaea Specific question for you, since the above comment was quite long for diagnostics.
 
So - the few remaining failures in the Ruby 3.0 branch seem related to the fact that Ruby 3.0 wants to freeze the whole hash of translation strings once loaded, and won't allow them to be modified on the fly in tests. 

Is it because of the way they're supplied to tests? Would it be fixed if we loaded the strings with ActiveRecord for each test rather than accessing the hash from the class method?

I noticed this class method in TranslationString, where it seems they are loaded. But idk.
```ruby
  def self.translations(locale)
    I18n.backend.load_translations if I18n.backend.send(:translations).empty?
    I18n.backend.send(:translations)[locale.to_sym][MO.locale_namespace.to_sym]
  end
```

**Comment by nimmolo** [comment]
Maybe we could make a separate method to access `translations_for_tests` that does not use the `I18N.backend`?

**Comment by nimmolo** [comment]
Ahhh... of course, our translations are not in the database. They're in locales/...yml files :)
Here's a thought... https://stackoverflow.com/questions/61012982/how-to-unfreeze-the-hash.
Maybe translations_for_tests could modify a `deep_dup`.

Or maybe translation updating via I18N gem needs to work a different way in Ruby 3.0. The gem is very actively maintained, so there must be a way. Still researching

**Comment by pellaea** [comment]
Thanks for prodding me.  I'd let this one slip by.  This is a concern.
It's not just the tests changing the translations on the fly.  There's a
mechanism on the site for editing translations live.  Those hashes *must*
be unfrozen one way or another, and not just in test mode.  I'm down with
replacing them with an unfrozen deep clone.  Is there a way to tell if a
hash is frozen in code?  We could have the bit in TranslationString check
if the hash is frozen before attempting to modify it, and if it is, replace
it with an unfrozen deep clone.  We might have to do something similar in
the tests, too.

**Comment by nimmolo** [comment]
Thanks. I am finding there may be a newish way to extend I18N.backend to do what we want. Still researching.

nimmo

**Comment by pellaea** [comment]
That would be awesome, and well worth a PR.  I feel like my current
solution is a kludge that is going to be problematic for us every time we
do a major upgrade.

**Comment by JoeCohen** [comment]
>
> Is there a way to tell if a hash is frozen in code?

Do you mean like frozen?
<https://ruby-doc.org/core-3.0.0/Kernel.html#method-i-frozen-3F>

**Comment by nimmolo** [comment]
A new thing with Ruby 3.0 (i believe) is that ALL hashes are frozen, if they do not contain dynamic elements.

This was done for performance improvement, and the whole new thing with default/enforced freezes is supposedly a big part of why it’s faster and uses less memory.

We can’t deep_dup our translations, though, because … i think… at present they are hashes nested in arrays. About to inspect one to find out.

I’ve seen solutions where people modify the i18N backend to return a hash of hashes (no arrays) always, then we just have to maybe tweak our access methods. Or maybe in Ruby accessing a hash by key is the same as an array by key?

nimmo

**Comment by nimmolo** [comment]
Interestingly, for example, I had to un(-explicitly)freeze a whole bunch of regex for the 3.0 branch, because they are frozen by default.

nimmo

**Comment by pellaea** [comment]
Thanks for the research Nimmo.  I see.  This may be a problem.  But
something occurs to me.  Maybe a less kludgy solution.  The only
translations we care about are the :blah.l tags.  How about instead of
trying to change the I18n structures, let's just create a mechanism that
overrides the tags that we've changed dynamically?  I can handle this
tomorrow morning if you like.  Or at least create a quick draft to share my
idea, if you'd prefer to do it.  Let's see what people think of it.

**Comment by nimmolo** [comment]
Before you try that, another thing occurred to me — there may be a method already available from the I18N class...
...Is [this](https://stackoverflow.com/a/25387302/3357635) what we want?`I18n.backend.store_translations(:en, {test: "YOOOOOHHHHHOOOO"})` (towards the end of the linked answer.) 

I haven't read through the I18N gem code but I know there must be more methods. Now it's my evening reading!
If this doesn't turn up anything, though, i'm very much in favor of your proposal. Will report back.

**Comment by nimmolo** [comment]
Ok. Yep, the gem [already implements `store_translations`](https://github.com/ruby-i18n/i18n/blob/b805537905522beb95ee7fc772fc8b6e150e1dbe/lib/i18n/backend/simple.rb#L33) in its Simple backend.

That implementation of `store_translations` dup's the hash to merge, using their [Utils](https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/utils.rb) class. Reading up on how to use it.

I guess the backend is extensible, because the ways of storing translations are highly variable.
Incidentally — translations are lazy loadable now, let me know if you have any interest in implementing that.

**Comment by nimmolo** [comment]
How do you guys feel about merging this? There are no big changes... It works, and Nathan's new Vagrant build `mo-focal-2022-06-04` is also working for Joe and me, with three Ruby versions (2.7.6, 3.0.4, 3.1.2) installed.

**Comment by JoeCohen** [comment]
I like the idea of getting this out, but can we do it tomorrow?
I'm concerned about something going wrong if it's deployed to the webserver. (E.g., must we first install/upgrade Ruby on the webserver? Must we take the website down while we do that?)
All of us should be around to help on Sat.

**Comment by nimmolo** [comment]
Sounds good! I dont believe any updates on master get deployed to production without Jason, in any case  Correct me if i'm wrong about that!

**Comment by pellaea** [comment]
We can install new versions of ruby without taking the webserver down.  But
installing the new bundle has to happen while the server is down.  It's
usually very quick, though.

I'd rather not make a habit out of letting master and the production server
differ.  So long as everyone is aware and remembers, yes, you're right,
it's safe.  But it is easy for someone to come in a push out a quick PR not
realizing that someone else had merged something into master that they
didn't want to deploy yet.  It has happened before.  Better to wait on
merging into master until just before it is deployed, in my opinion.  You
are free to merge it into other PRs in the meantime, so it shouldn't hold
anything back.

**Comment by JoeCohen** [comment]
@nimmolo: I often deploy master to production when master has bug fixes / new features.
> Sounds good! I dont believe any updates on master get deployed to production without Jason, in any case Correct me if i'm wrong about that!

**Comment by JoeCohen** [comment]
I just discovered that we need to tweak our CI Github Action in order to work with Ruby 3.x.
See https://github.com/actions/setup-ruby#readme
I will try to fix things up and get back to everyone.

**Comment by JoeCohen** [comment]
False alarm. We have the right actions.
A comment had a link to a deprecated action. I'll update that.

**Comment by pellaea** [comment]
Yes, exactly like that!  Thanks.

**Pull request merged**
