### PR TITLE
Refactor `ObserverController`

### PR DESCRIPTION
**Pull request by nimmolo**
This creates several new controllers (and controller tests) out the original `ObserverController` components.
`AdminController`
`AuthorsController`
`ChecklistsController`
`ContributorsController`
`EmailsController`
`ExportController`
`InfoController`
`JavascriptController`
`LookupsController`
`RssLogsController`
`SearchesController`
`UsersController`
~It also "normalizes" a new `ObservationsController`~

### CODE REVIEW

**Comment by nimmolo** [comment]
@pellaea @JoeCohen per today's meeting, I believe this PR is good to go. 
Free to merge whenever you feel ready.

(The `ObservationsController` PR can go separately, in any case it is encountering more issues.)

**Comment by pellaea** [comment]
Meaning no lack of respect for the amount of work you've done here, Nimmo -- quite the opposite! -- but I cannot bear to read through all the changes in this PR again!  I'm good with merging this into master and pushing it out live whenever you all are ready.  Joe, are you okay with that, too?

**Comment by JoeCohen** [comment]
There's one more easily fixable Codeclimate issue.
I'll get to it within 30 minutes, then merge and deploy.

**Comment by JoeCohen** [comment]
Fixed issue, but 1/2 CI test runs inexplicably failed. 
I restarted it.
When it passes I'll merge & deploy.

**Comment by JoeCohen** [comment]
It's merged.
But it also just occurred to me that I might have misread Jason's message.
In particular, he might have wanted to merge and deploy it himself, or at
least be around when it was deployed.
It would be safer that way.
So I'll wait on deploying it until I hear back from him.

**Pull request merged**
