### PR TITLE
Fixing line endings! +Test reporting

### PR DESCRIPTION
**Pull request by raysuelzer**
I'm not entirely sure this will pass travises muster.  my goal is here is to normalize all of our files to have the same line endings, LF.

I also added minitest-reporter so that results from tests will appear in IDEs like Rubymine.

### CODE REVIEW

**Comment by raysuelzer** [comment]
Passed finally. Thank god.

**Comment by mo-nathan** [comment]
That's weird.  I just checked out this branch and when I ran 'rake' it started downloading something:

$ rake
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.
Run options: --seed 29
Started

189/1193: [=====                            ] 8.3/s 15% 00:00:34, ETA: 00:02:01

Any idea what would cause this?

I had already run "bundle install".

**Comment by mo-nathan** [comment]
Oh, weird.  I guess this is just how tests run now.

**Comment by JoeCohen** [comment]
For a long time (> 6 months), tests have started like this:
```
vm:mushroom-observer$ rake
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.
Run options: --seed 40219
```
The new stuff:
```
Started
189/1193: [===== ] 8.3/s 15% 00:00:34, ETA: 00:02:01
```
is almost certainly from the newly-installed minitest-reporters gem.

**Pull request merged**
