### PR TITLE
Replace observation search param `has_location` with `has_public_lat_lng`, fix search instructions

### PR DESCRIPTION
**Pull request by nimmolo**
Until now, we don't have a parameter to search for obs with geolocation. We do however have a query param `has_location` which is currently not very useful. Addresses #2093. 

Now incorporates #2096, renaming `long` to `lng` everywhere, because it's tangentially relevant to this PR.

#### Questions: ####
- should a query like this also check for `gps_hidden`? I believe so.
I had thought not, because on my checkpoint the lat/lng seems to have been stripped where `gps_hidden`. But Joe pointed out that the lat/lng is saved on the obs even when `gps_hidden`, on production.
- should it instead be called `has_public_geolocation`?

### CODE REVIEW

**Comment by nimmolo** [comment]
Please vote for a name for this param:
- `gps_public`
- `has_geolocation`
- `has_public_geolocation`
- `has_lat_lng`
- `has_public_lat_lng`

**Comment by pellaea** [comment]
My 2¢ = `has_public_lat_long` because that is least ambiguous.

**Comment by nimmolo** [comment]
Per email conversation with @pellaea it seems the `has_location` param is only useful for finding undefined Locations.  That query returns only one observation in the entire database with an undefined location currently (and it's from the town I live in!)

**Comment by nimmolo** [comment]
@JoeCohen should we retire `has_location`?

**Comment by JoeCohen** [comment]
param name:
I'm good with whatever others like. If it were up to me I'd use something without "has" (will avoid one rubocop issue).
maybe `with_public_geolocation`

I'm OK with retiring `has_location`.

**Comment by nimmolo** [comment]
@mo-nathan is the `has_location` query param useful for projects, or anything you're working on? 

In case you missed the discussion on this, `has_location` only checks for an associated location, which of course could be "Alabama, USA", so it's not so useful, except for finding obs with undefined location. 

The current use people seem to have for something like this, however, is trying to find observations that "have a precise and public GPS lat/long". Until now, the search instructions for the `has_location` param erroneously suggested this was what it did.

**Review by mo-nathan — APPROVED** [review]
Looks good to me.

**Review by JoeCohen — APPROVED** [review]

**Pull request merged**
