### PR TITLE
Make `where` string search use its own, non-conflicting param

### PR DESCRIPTION
**Pull request by nimmolo**
This resolves a conflict in the Observations controller about which param sets which query/scope.

`location` is now used for location_id, `where` for the where string, and `user_where` for the advanced search which may search either place, plus location notes. (I have no idea how useful that is in MO experience, but it's there.)

Not asking for code review, but please test 
- Location observation searches
- Corresponding searches of Images or Names of Observations at locations
- Location content filters and 
- Location Advanced Searches

The reason for the PR is preparation for the AR switch, and removing confusing code.

NOTE: I plan to add coverage of the Species List sorting lines, which I think actually might throw an error.

### CODE REVIEW

**Comment by JoeCohen** [comment]
This could be old. 
- http://localhost:3000/observations?pattern=user%3A4468
- Show Locations
- click Barlow Ranger District portion in Wasco Co., Mount Hood National Forest, Wasco Co., Oregon, USA (54)
- click Observations at this Location (54)
- click Show Locations

Expected result:
> Locations with Matching Observations
...
[Barlow Ranger District portion in Wasco Co., Mount Hood National Forest, Wasco Co., Oregon, USA (54)](http://localhost:3000/locations/22494)

Actual Result:
```ruby
NoMethodError in LocationsController#index
undefined method `map' for an instance of Integer
Did you mean?
tap
Extracted source (around line #44):
              
      #    where(<x>.in(limited_id_set(ids)))
      def limited_id_set(ids)
        ids.map(&:to_i).uniq[0, MO.query_max_array]
      end

      # Clean a pattern for use in LIKE condition.  Takes and returns a String.

Rails.root: /Users/joe/mushroom-observer

Application Trace | Framework Trace | Full Trace
app/classes/query/modules/initialization.rb:44:in `limited_id_set'
app/classes/query/modules/initialization.rb:37:in `clean_id_set'
app/classes/query/modules/conditions.rb:105:in `add_id_condition'
app/classes/query/location_with_observations.rb:51:in `add_where_conditions'
app/classes/query/location_with_observations.rb:40:in `initialize_flavor'
app/classes/query/modules/initialization.rb:22:in `initialize_query'
app/classes/query/modules/low_level_queries.rb:31:in `select_values'
app/classes/query/modules/high_level_queries.rb:56:in `result_ids'
app/classes/query/modules/high_level_queries.rb:36:in `num_results'
app/controllers/application_controller/indexes.rb:245:in `set_index_view_ivars'
app/controllers/application_controller/indexes.rb:206:in `show_index_setup'
app/controllers/application_controller/indexes.rb:189:in `show_index_of_objects'
app/controllers/application_controller/indexes.rb:117:in `filtered_index'
app/controllers/application_controller/indexes.rb:28:in `block in build_index_with_query'
app/controllers/application_controller/indexes.rb:17:in `each'
app/controllers/application_controller/indexes.rb:17:in `build_index_with_query'
app/controllers/locations_controller.rb:29:in `index'
app/controllers/application_controller.rb:218:in `catch_errors_and_log_request_stats'
```

**Comment by JoeCohen** [comment]
Advanced Search
Result Type: Observations
Name: `Morchella snyderi`
Location: `Barlow Ranger District portion in Wasco Co., Mount Hood National Forest, Wasco Co., Oregon, USA`

Result:
(I think it's showing all Obss of _M. snyderi_.)
Many Observations of _M. snyderi_, of which only a fraction are in the selected Location.

**Review by JoeCohen — COMMENTED** [review]
Spent a lot of time trying different searches. See my comments for buggy results.

**Comment by nimmolo** [comment]
@JoeCohen Thank you very much for these catches. Both fixed now, I believe.

I will write integration tests for them both before merging. 
The code these same links use would be changed again in the AR scope phase.

**Pull request merged**
