### PR TITLE
Assignment in Condition

### PR DESCRIPTION
**Pull request by JoeCohen**
This PR fixes all existing (Lint/AssignmentInCondition)[https://docs.rubocop.org/rubocop/cops_lint.html#lintassignmentincondition] offenses.

The result is that the cop is re-enabled and the offense count is reduced by 34.

### CODE REVIEW

**Comment by JoeCohen** [comment]
Reviews are welcome if you have the desire. 
The changes are simple (just putting parens around the condition), but review is boring to mind-numbing.
I''ll probably merge it in a day or so unless there are objections.

**Comment by nimmolo** [comment]
Looks good to me.
I don't mind reviewing... it's a way to find out what Rubocop prefers.

**Comment by pellaea** [comment]
Sorry, I looked at this the other day (yesterday?)  It is really straightforward.  I forgot to leave a comment passing on my completely superfluous approval!

**Comment by JoeCohen** [comment]
Thanks @nimmolo & @pellaea.
I'll merge it.

**Pull request merged**
