### PR TITLE
Repair observation form map

### PR DESCRIPTION
**Pull request by nimmolo**
**Please test drive.** Works for me locally.

I was trying to pass a jQuery object to Google Maps.  Gmaps can only deal with a vanilla JS object, not a jQuery object.

This also renames the div, and fixes a bunch of leftover references to the incorrect login page url.

### CODE REVIEW

**Comment by JoeCohen** [comment]
Thanks for jumping on this.
I re-ran the failed job to get it pass. 
The code will be beyond me (I'm a js ignoramus), but I'll test drive it in the next 5-10 minutes.

**Comment by JoeCohen** [comment]
I still get a hanging spinner (when running locally in dev mode).

**Comment by nimmolo** [comment]
@JoeCohen Hm. Just switched branches and tried again, it's working here. 

Maybe try a private window?
If that doesn't work: do you get any errors in the js console?

**Comment by JoeCohen** [comment]
I tried a Chrome anonymous window and a Firefox private window, but it still hangs.
Being a js ignoramus, I don't knowhow to use the js console. Is is this:
Screenshot 2023-01-08 at 3 02 45 PM

**Comment by nimmolo** [comment]
That's the console yes. 👍
Thank you for checking. 
And you're sure you're on the right branch... (?) just checking because i personally forget where i am 24 times a day.

I will switch browsers and report back.

**Comment by JoeCohen** [comment]
This is weird. I'm in the right branch, but I'm not seeing your commits.
I will try restarting VScode and re-fetching the PR to see if I can get to the right state.
```sh
$ git status
On branch nimmo-fix-name-tracker-test-emails
Your branch is up to date with 'origin/nimmo-fix-name-tracker-test-emails'.

nothing to commit, working tree clean
vagrant@ubuntu-focal /vagrant/mushroom-observer (nimmo-fix-name-tracker-test-emails)
$ git log
commit ff5b09cd0a7336ab54e939ecfa7843af6f57da43 (HEAD -> nimmo-fix-name-tracker-test-emails, origin/nimmo-fix-name-tracker-test-emails)
Author: Joe Cohen <jdcohenesq@gmail.com>
Date:   Sat Jan 7 22:39:30 2023 +0000

    Delete stray comment
...
```

**Comment by JoeCohen** [comment]
OOPS. That's the wrong branch.

**Comment by JoeCohen** [comment]
It works in the right branch. 
Sorry for the false alarm.

**Review by JoeCohen — APPROVED** [review]

**Pull request merged**
