### PR TITLE
Modernized app/views/account/*

### PR DESCRIPTION
**Pull request by pellaea**
Also fixed bug in api key manager: jquery.show() doesn't seem to be able to show something hidden with class="hidden".  Changed it to "display:none" and now jquery.show() can manage it.  Weird.  I could've sworn this worked before.

Also added data-autofocus as an alternative to plain vanilla autofocus.  I don't know about other browsers, but autofocus causes firefox to scroll stupidly down the page, hiding the title and stuff.  If instead wewait until the page is loaded and then focus on the first element with data-autofocus=true, then it just focuses without scrolling.

### CODE REVIEW

**Comment by raysuelzer** [comment]
Yeah, it's annoying.  Check out bootstraps css for hidden.  jQuery doesn't
change the visibility or override the !important.


.hidden { display: none !important; visibility: hidden !important;}


Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
Oh, is that why?  I figured jquery changed both visibility and display, but
didn't consider !important.  Out of curiosity, how would you override an
!important styling in javacsript / jquery?

**Comment by raysuelzer** [comment]
you'd have to do
$('#foo').style('display', 'block');
$('#foo').style('visiblity', 'visible');

but if you really just want to hide or unhide things in bootstrap it's
easiest to use  $('#foo').toggleClass('hidden');

Ray Suelzer
Mobile: (312) 869-2665

**Comment by raysuelzer** [comment]
vanilla javascript would be something like:
 document.getElementById('foo').style.visibility = 'visible';      i
think...

Ray Suelzer
Mobile: (312) 869-2665

**Pull request merged**
