### PR TITLE
Added fix for pathological case…

### PR DESCRIPTION
**Pull request by pellaea**
... in which a user is logged in while sending an account verification email.

### CODE REVIEW

**Comment by JoeCohen** [comment]
I'm OK with the "cheesy" fix to stop the errors.
Another option?  This is a fairly recent bug (3 weeks?). Can we figure out where it was introduced?

**Comment by pellaea** [comment]
Yeah, I think I know.  Verification emails used to not be queued.  So this
would never have been an issue.  It would have started when Nimmo changed
it into a QueuedEmail.  So, reversion is not an option (that I'm willing to
consider).

**Comment by JoeCohen** [comment]
Thanks! I agree.

**Comment by pellaea** [comment]
And I think I might know sorta why it's happening to start with.  I wonder
if the user is getting impatient and is asking for multiple verification
emails, and accidentally submitting one of those after they've successfully
verified?  I don't understand in detail because I still don't understand
the new routes.  But since the verification email is created in only one
place -- AccountController#create -- I assume reverification must also
somehow be hitting that route, too.  Nowhere do we explicitly set @user =
User.current = nil in that action, so if a user were to visit that route
while logged in, it would result in this error.  There should be no visible
links to that route once the user is logged in, but if they have an old
page open from before logging in, it could potentially happen.

Hmmm.  Does that mean we should actually kick the user out of
AccountController#create if they are already logged in??  Sort of the
opposite of login_required -- login_forbidden? ;)  Maybe send them to the
home page or the welcome page instead?  *That* would be a cleaner way to
solve the problem, maybe.

**Pull request merged**
