### PR TITLE
Disable other value unless radio button is selected.

### PR DESCRIPTION
**Pull request by pellaea**
And cleaned up / standardized syntax, removed tabs from donate view.

(Sorry, Nathan, broke my proposed rule of not mixing cleaning and coding.  Didn't take long to prove myself hypocritical...)

### CODE REVIEW

**Comment by mo-nathan** [comment]
This is enough to get me going in the right direction.  I don't want to merge it as is since I've realized that it already refers to a JS file, donate.js, that isn't currently in the code base (but maybe it used to be?).  That seems like a logical place to put this new code.  Also while the new interaction is better, it seems like we may as well go a bit further such as making it so that clicking on the text box moves the radio button selection rather than it being disabled and maybe the input should be constrained to be numeric.

**Comment by pellaea** [comment]
So, this may be pathological, but it is possible to circumvent your onclick event on other-value.  You can _tab_ into the text field, then enter an amount and submit the form.  You could, I suppose, watch onchange for that text field, too.

Sorry to be negative, but I can also see confusion if someone quickly types "100.00" and submits then finds themselves surprised when MO wants to deduct $10K from their bank account(!)  It's kinda fun to play with this callback which prevents you from typing anything except digits, but it's a bit odd.  Brilliantly simple!  But feels strange to me personally.

Feel free to ignore both complaints.

**Comment by mo-nathan** [comment]
The recurring donations are handled by PayPal.  We don't have to do anything.

I also think the other concerns are also reasonably addressed by the PayPal confirmation process.  However, if you can think of an easy way to make these better, that would be great.  However, I think this is ready to ship as it is and I want to get it out before the end of the year so folks can use it if they want.

**Comment by pellaea** [comment]
Agreed, I'm fine with paypal catching any (extremely rare) stingers.  Glad
this is out.  Progress, whee!

**Pull request merged**
