### PR TITLE
Added script to automatically backup the database.

### PR DESCRIPTION
**Pull request by pellaea**
I changed it to store the snapshots on the image server, so there is no manual test now, sorry.

It keeps 7 daily backups, 8 weekly backups, 12 monthly backups, all yearly backups, and it removes anything else from the backup directory.  This will soon take up ca. 10 GB of disk space, but that's a drop in the bucket on the image server, so I don't anticipate any problems.

### CODE REVIEW

**Comment by JoeCohen** [comment]
My instinct is to store them on the image server.

**Comment by pellaea** [comment]
Changed script to store the snapshots on the image server.  It's a lot harder to test and potentially more dangerous.  The delete command at the end really wigs me out.  For example, if something goes wrong and it's not able to create the backup directory remotely, it can return a listing of everything in mo's home directory on the image server, and then attempt to delete it all.  I'll add sanity checks in a few places to prevent that from happening.

**Comment by JoeCohen** [comment]
Would the GoogleCloud be any better?

**Comment by pellaea** [comment]
Google Cloud is a good idea.  However it's harder ... if we want to keep the snapshots down to a reasonable number.  If we just stuff snapshots into the cloud every day... oh wait, we would need to encrypt them, then, too.  There is sensitive information in these snapshots.

I'm pretty happy with this script now.  I think the new assertions prevent anything crazy or unexpected from happening.

**Comment by JoeCohen** [comment]
Oops. I forgot about encryption.

**Comment by pellaea** [comment]
Yeah, I think these will be more convenient to use when and if we need them
later.

**Comment by mo-nathan** [comment]
Look great to me!

**Comment by pellaea** [comment]
Cool.  I'll let 'er loose tonight.

**Pull request merged**
