### PR TITLE
Moved to the bootstrap-sass gem.

### PR DESCRIPTION
**Pull request by pellaea**
Also moved the vast majority of the "configurable" details (colors, borders mostly) into variables which will make writing themes much much easier.  Presently only BlackOnWhite and Agaricus are available.

### CODE REVIEW

**Comment by raysuelzer** [comment]
Great.  I'm sure we will find a few things that need to be changed, but we
are going to find them faster if we are all looking at it.

Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
I'm having great difficulty merging bootstrap in.  This will take some
time.  I don't recall changing any views except the layout and left_nav and
search_bar partials.  I need to see what got changed in these other files
(e.g. show_name) to see which version is "correct"...

**Comment by raysuelzer** [comment]
I think I edited those on accident when trying to figure out how to push
your branch to my remote (something with stash and unstash?).  Anyway, use
the version in ror4.


Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
Uh oh!  Are you sure? :)  They're fairly major!

**Comment by raysuelzer** [comment]
Yeah it should be a total revision.  It got put into your branch... I am
bad with git.

Ray Suelzer
Mobile: (312) 869-2665

**Pull request merged**
