### PR TITLE
Backfill original_name

### PR DESCRIPTION
**Pull request by JoeCohen**
This is a script to ensure that images imported from iNat photos have a unique `original_name`.
- Adds the iNat `photo_id` and `uuid` to the `original_name` of Images which were imported from iNat photos prior to Fri Dec 13 15:03:37 2024 -0800. (Later imports already have the desired `original_name`.)
- The point is enabling efficient syncing/updating of Observations.
- This is a run-once script which can be deleted after it's run.

NOTE: Some `original_names` cannot be fixed. Either:
- The photo has been deleted from iNat. 
- The entire iNat observation has been deleted.

### CODE REVIEW

**Comment by JoeCohen** [comment]
This PR isn't a thing of beauty, but it works -- I manually tested it locally -- and will be used only once.
I therefore prefer to avoid investing time time to make it pretty.
It takes about 10 minutes to run, primarily because it hits the iNat API no more than once per second, per iNat's request to "eep it to 60 requests per minute". (There are about 600 relevant Observations, and I'm hitting the iNat API ~once per Observation.)

### Question
Should this be turned into a Job?

**Comment by JoeCohen** [comment]
#### QUESTION
Is it worth the effort to turn this into a background Job?

This isn't a thing of beauty, but 
- It works (I tested it manually in the dev environment).
- It will be used only once.

I therefore prefer to avoid investing time to make it pretty.

It takes about 10 minutes to run, primarily because iNat asks: "keep it to 60 requests per minute", I'm hitting that API once per O)bservation, and there about 600 relevant Obss.

**Comment by nimmolo** [comment]
Sounds like no need to make it a job. Good to go, IMO.

**Comment by JoeCohen** [comment]
Thanks for looking at it and the comments.

**Comment by mo-nathan** [comment]
This is a one time thing, right?  If so, then I wouldn't merge it into main, but rather copy it over to the server and run it.  You can leave it on this branch as a record of what was done, but I don't think there is value in merging it into main.

**Comment by JoeCohen** [comment]
Thanks. Will do.

**Comment by JoeCohen** [comment]
Closing this per @mo-nathan's suggestion.

**Pull request closed without merging**
