### PR TITLE
Add a `field_slip` keyword to Observations PatternSearch

### PR DESCRIPTION
**Pull request by nimmolo**
Allows users to type this in the search field and get back the relevant observation:

`field_slip:ATEST-0001`

### CODE REVIEW

**Comment by mo-nathan** [comment]
`RuntimeError in ObservationsController#index
Don't know how to join from observations to field_slips.
Extracted source (around line #265):
            from, to = to, from
          else
            raise("Don't know how to join from #{from} to #{to}.")
          end

          # By default source table column is just "id"; enter both target and
Rails.root: /Users/nathan/src/mushroom-observer

[Application Trace](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#) | [Framework Trace](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#) | [Full Trace](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/joining.rb:265:in `calc_join_condition'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/sql.rb:123:in `calc_join_conditions'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/sql.rb:121:in `block in calc_join_conditions'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/sql.rb:121:in `map'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/sql.rb:121:in `calc_join_conditions'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/sql.rb:74:in `calc_from_clause'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/sql.rb:25:in `query'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/low_level_queries.rb:35:in `select_values'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/high_level_queries.rb:56:in `result_ids'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/classes/query/modules/high_level_queries.rb:36:in `num_results'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/application_controller.rb:1437:in `set_index_view_ivars'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/application_controller.rb:1399:in `show_index_setup'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/application_controller.rb:1375:in `show_index_of_objects'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/observations_controller/index.rb:189:in `show_selected_observations'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/observations_controller/index.rb:131:in `render_pattern_search_results'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/observations_controller/index.rb:117:in `pattern'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/application_controller.rb:1335:in `block in index'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/application_controller.rb:1333:in `each'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/application_controller.rb:1333:in `index'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)
[app/controllers/application_controller.rb:226:in `catch_errors_and_log_request_stats'](http://localhost:3000/observations?pattern=field_slips%3AATEST-00002#)

**Comment by mo-nathan** [comment]
Working better.  This PR should target main now that njw-field-slip-pdfs has merged.

**Comment by mo-nathan** [comment]
Even after merging in main locally this PR is failing a lot of tests.  I haven't dug into why.

**Comment by nimmolo** [comment]
@mo-nathan — @pellaea spotted the problem. 

My query method needed a guard clause so it only gets applied if there IS a field_slip param.

**Pull request merged**
