### PR TITLE
New Relic

### PR DESCRIPTION
**Pull request by JoeCohen**
New Relic for application monitoring. See https://newrelic.com/, https://docs.newrelic.com/

Additional steps needed to implement monitoring (after this PR is merged):
1. Add the actual license key to the web server in file that's not under version control or using the new Railsy secrets mechanism.
2. Restart the webserver.
3. Connect New Relic with our logs and infrastructure. (Requires logging into New Relic to get customized file to install on webserver.)
4. Use New Relic's "See your data" button. (Also requires New Relic login.)
(Contact me for login info.)

There is no manual test.

### CODE REVIEW

**Comment by mo-nathan** [comment]
Looks reasonable to me.

**Comment by JoeCohen** [comment]
Thanks for the feedback.

**Comment by JoeCohen** [comment]
Hi Nimmo.
It runs only on the webserver.
I set it up to run only in the production environment, but I suppose it makes sense to allow it in development (also on the webserver).
I think it sends data from the webserver to New Relic; the data can be viewed through the New Relic dashboard.
I don't know what data it sends or how to configure the dashboard.
It was recommended at least by @gete76, and @mo-nathan said he'd heard good things about it.
@gete76 will help configure the dashboard once it's running.
- Joe

**Comment by nimmolo** [comment]
Thanks for the explanation. I dimly remember working on a project that had NR installed, but i never knew how it was doing what it did. On Dec 19, 2022, at 9:37 PM, Joseph D. Cohen ***@***.***> wrote:﻿
Hi Nimmo.
It runs only on the webserver.
I set it up to run only in the production environment, but I suppose it makes sense to allow it in development (also on the webserver).
I think it sends data from the webserver to New Relic; the data can be viewed through the New Relic dashboard.
I don't know what data it sends or how to configure the dashboard.
It was recommended at least by @gete76, and @mo-nathan said he'd heard good things about it.
@gete76 will help configure the dashboard once it's running.

Joe

**Pull request merged**
