### PR TITLE
Fixed all the buttons throughout the site.

### PR DESCRIPTION
**Pull request by pellaea**
Fixed some theme-related stuff.
BlackOnWhite should be unchanged, if it did, I messed something up(!)

### CODE REVIEW

**Comment by raysuelzer** [comment]
Well the buttons now have gradients.

Ray Suelzer
Mobile: (312) 869-2665

**Comment by raysuelzer** [comment]
And border radius.  but it looks fine, just a little 2010 ;)

Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
You are welcome to change it!  The point was they were different on each
page.  Now they can be styled, and they will all be the same throughout the
site, whatever you choose.  Flat it easy to do, if you'd like to go back to
what they were.  But you can also add the sassy-buttons gem to get some
cool "glass" effects, etc.  I'm not trying to make stylistic decisions
here, just trying to make things consistent and configurable.  There are
still a couple, e.g., on list_rss_logs, which are not configurable.  But
I've gotten all the submit buttons at least, plus several others.

**Comment by pellaea** [comment]
There you go, default theme is back to what it was.

**Comment by raysuelzer** [comment]
It's totally fine. I was just playing, it looked just fine.  Only things
that offend me are not enough white space and long blocks of text.

Ray Suelzer
Mobile: (312) 869-2665

**Comment by pellaea** [comment]
Sorry, must've been oversensitive because of the sheer amount of effort
required to add "btn" class to every freaking button on the site!! :)


Struggling with checkboxes on rss log "tabs".  On firefox they make the
buttons too big vertically, very unsightly, but refuses to shrink, grrr...

**Comment by raysuelzer** [comment]
Try...

.btn-sm, .btn-group-sm > .btn {
    font-size: 12px;
    line-height: 1.5;
*    padding-top: 1px;*
*    padding-bottom: 1px;*
}

Ray Suelzer
Mobile: (312) 869-2665

**Pull request merged**
