### PR TITLE
Remove support for IE < 11

### PR DESCRIPTION
**Pull request by nimmolo**
Removes the `single_image_upload.js` script and associated form `observations/form/images_upload/mono.html.erb`.

Removes the helpers `javascript_helper.rb#modern_browser?`, `#can_do_ajax?`, and `#can_do_multifile_upload?` and the very few calls to these.

### CODE REVIEW

**Comment by nimmolo** [comment]
The `ObservationFormIntegrationTest#test_post_edit_and_destroy_with_details_and_location` only tests the single image upload form, because we don't have Capybara running with JS yet. 

The sooner we can get that working, the better.

**Comment by JoeCohen** [comment]
If you can suggest some manual tests, I'll try it out.

**Comment by nimmolo** [comment]
@JoeCohen - this would mean getting a test case class working that uses Firefox headless, that we discussed in another thread. We can't test the image uploader without that. 

I believe you could handle it, it's just troubleshooting why the test case won't load properly (Ruby errors).

**Comment by JoeCohen** [comment]
I meant a manual test.

**Comment by nimmolo** [comment]
There's no manual test that will fix the failing integration test on this branch. It needs Capybara working on all cylinders.

**Comment by JoeCohen** [comment]
Gotcha. We were talking about two different things.

**Pull request merged**
