### PR TITLE
Update Codeclimate tools

### PR DESCRIPTION
**Pull request by JoeCohen**
- Updates Rubocop to 1.42
- Re-arranges Gemfile to remove Codeclimate tools from Production environment
- Fixes new Rubocop offenses, updating Rubocop todo list.
- There are 3 new cops
  - [Style/MapToSet](https://docs.rubocop.org/rubocop/cops_style.html#stylemaptoset)
  - [Style/MinMaxComparison](https://docs.rubocop.org/rubocop/cops_style.html#styleminmaxcomparison)
  - [Style/YodaExpression](https://docs.rubocop.org/rubocop/cops_style.html#styleyodaexpression)

If anyone hates any of these (especially Style/YodaExpression) please let me know and I'll disable it.

There are no manual tests.

### CODE REVIEW

**Comment by JoeCohen** [comment]
[Order-dependent failure, reproducible locally with seed 53296](https://github.com/MushroomObserver/mushroom-observer/actions/runs/3833907558/jobs/6525784757#step:13:7):
```ruby
Run bundle exec rails test
Started with run options --seed 53296

FAIL CommentTest#test_user_highlighting_emails (89.93s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:36:in `do_highlight_comment_where_mary_opts_in'
        test/models/comment_test.rb:24:in `test_user_highlighting_emails'

 FAIL CommentTest#test_comment_notification (90.04s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:66:in `do_comment_response_where_mary_opts_in'
        test/models/comment_test.rb:53:in `test_comment_notification'

Finished in 21[7](https://github.com/MushroomObserver/mushroom-observer/actions/runs/3833907558/jobs/6525784757#step:13:8).93592s
2139 tests, 2[8](https://github.com/MushroomObserver/mushroom-observer/actions/runs/3833907558/jobs/6525784757#step:13:9)054 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by JoeCohen** [comment]
It's okay at the merger of #1260:
```ruby
vagrant@ubuntu-focal /vagrant/mushroom-observer  ((HEAD detached at fcc916e0e))
$ rails t --seed 53296
Started with run options --seed 53296

grep: /vagrant/mushroom-observer/log/test.log: No such file or directory   ] 22% Time: 00:01:11,  ETA: 00:04:08
  2139/2139: [============================================================] 100% Time: 00:04:36, Time: 00:04:36

Finished in 276.60047s
2139 tests, 28032 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by JoeCohen** [comment]
Tests break with the merger of #1254 (ImagesController CRUDIFY)
Moreover, if I run the tests with the bad seed, after 2019 assertionsthe tests freeze  (and my laptop fan goes into ramjet mode):
```ruby
vagrant@ubuntu-focal /vagrant/mushroom-observer  ((HEAD detached at 413364325))
$ rails t --seed 53296
Started with run options --seed 53296

 FAIL CommentTest#test_user_highlighting_emails (114.96s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:36:in `do_highlight_comment_where_mary_opts_in'
        test/models/comment_test.rb:24:in `test_user_highlighting_emails'

 FAIL CommentTest#test_comment_notification (115.11s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:66:in `do_comment_response_where_mary_opts_in'
        test/models/comment_test.rb:53:in `test_comment_notification'

  2139/2019: [=========================================================    ] 94% Time: 00:04:08,  ETA: 00:00:15
```

**Comment by JoeCohen** [comment]
nimmo-CRUD-2-images-controller #1253 broken at least as far back as d40a61327
```ruby
vagrant@ubuntu-focal /vagrant/mushroom-observer  ((HEAD detached at d40a61327))rails t --seed 53296
Started with run options --seed 53296

 FAIL CommentTest#test_user_highlighting_emails (111.34s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:36:in `do_highlight_comment_where_mary_opts_in'
        test/models/comment_test.rb:24:in `test_user_highlighting_emails'

 FAIL CommentTest#test_comment_notification (111.51s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:66:in `do_comment_response_where_mary_opts_in'
        test/models/comment_test.rb:53:in `test_comment_notification'

  2139/2019: [=========================================================    ] 94% Time: 00:04:22,  ETA: 00:00:16
```

**Comment by JoeCohen** [comment]
nimmo-CRUD-2-images-controller #1254 broken at least as far back as d40a61327
```ruby 
vagrant@ubuntu-focal /vagrant/mushroom-observer  ((HEAD detached at 37dd6f43c))
$ rails t --seed 53296
Started with run options --seed 53296

 FAIL CommentTest#test_user_highlighting_emails (106.59s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:36:in `do_highlight_comment_where_mary_opts_in'
        test/models/comment_test.rb:24:in `test_user_highlighting_emails'

 FAIL CommentTest#test_comment_notification (106.75s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:66:in `do_comment_response_where_mary_opts_in'
        test/models/comment_test.rb:53:in `test_comment_notification'

  2139/2019: [=========================================================    ] 94% Time: 00:04:05,  ETA: 00:00:15
```

**Comment by JoeCohen** [comment]
With the bad seed, `Comment.create!` is not incrementing `num_emails` (which is simply ActionMailer::Base.deliveries.length).
At the moment, I can't figure out how to debug this further.  (Could some prior test be setting a flag that tells MO not to deliver emails?)
```ruby
 FAIL CommentTest#test_user_highlighting_emails (112.05s)
        No emails were sent.
        Expected: 1
          Actual: 0
        test/models/comment_test.rb:121:in `do_comment_test'
        test/models/comment_test.rb:36:in `do_highlight_comment_where_mary_opts_in'
        test/models/comment_test.rb:24:in `test_user_highlighting_emails'
```
```ruby
  def do_comment_test(chg, obs, user, summary, comment = "")
    old = num_emails
    obs&.reload # (to ensure it sees chgs in user prefs)
    Comment.create!(
      target: obs,
      user: user,
      summary: summary,
      comment: comment
    )
    assert_equal(chg, num_emails - old, sent_emails(old))
  end
```

**Comment by nimmolo** [comment]
Hi Joe! It’s fixed. Just merged it.

**Comment by JoeCohen** [comment]
Super!
Thanks for jumping on this and figuring it out.
It would have taken me forever.

**Comment by JoeCohen** [comment]
I will merge this branch this weekend. 
If you don't any of the new cops, please let me know or feel free to disable/re-configure them.

**Pull request merged**
