### PR TITLE
External link helper

### PR DESCRIPTION
**Pull request by JoeCohen**
[Delivered #146927773]
- Create file to house all external link helpers (methods which create links to external sites)
- Move all such helpers to that file
- Create additional helpers (for Google Image searches & EOL searches)

Suggested Manual Testing:
- Go to 1 or 2 Observation pages, and make sure the external links work.  
- Ditto for some Name pages

### CODE REVIEW

**Comment by pellaea** [comment]
Thanks, Joe.  This sounds like a good idea.  I'll have a look tomorrow.

**Comment by JoeCohen** [comment]
I did this branch because: I've been working (slowly) on a `sequences` branch, wanted to do this for that branch, thought it would be best to do all at once and avoid potential conflicts. 

All changes are on the View face of the MVC triangle (and in tests).

**Comment by JoeCohen** [comment]
Hold on. I want to think about this some more. Maybe part (the urls) belongs in Name &/or Sequence model(s).

**Comment by pellaea** [comment]
I haven't had time to look at it yet, sorry.

**Comment by JoeCohen** [comment]
Just as well. I'm pretty sure I'm going to change it.

**Pull request closed without merging**
