### PR TITLE
Update rails gems to 6.1.7.6

### PR DESCRIPTION
**Pull request by nimmolo**
Current results of `bundle update`. Resolves low-severity security alert in #1578.

@JoeCohen This may resolve the issue you were having. I am guessing an issue was that an `irb` update requires `rdoc` which requires `psych`.

Note: with this `minitest` update, `MiniTest` class is now `Minitest` (note only one cap). Thus the changes in a few references to `Minitest`.

### ~Possible production server update required?~ ###
~The vagrant box running focal required `port install libyaml +universal` to install the gem `psych`. Discussion below.~

The above seems to be fixed by locking `psych` at  `"~> 4"`.

### CODE REVIEW

**Comment by JoeCohen** [comment]
Nimmo:
Thanks for doing this. It looks good.
BUT I'm concerned about how it will behave on the webserver, because
`bundle install` blows up on my VM.
It's interesting that it works in CI without explicitly applying the fix
you mentioned here
<https://groups.google.com/g/mo-developers/c/99uiwN8ymuY/m/F3uvfEYoEgAJ>.
- Joe

**Comment by nimmolo** [comment]
Hm. And you tried restarting the VM with `vagrant halt` or `vagrant reload`?

**Comment by JoeCohen** [comment]
Good question. I haven't done that. Will retry now.

**Comment by JoeCohen** [comment]
Tried it, and it didn't work. Same old problem. See below.
And the same thing happens on my laptop.
I will see if I can make any progress after dinner.

$ git log -1
>
> commit 57581346bccc411ee5522a796741aac3b2d89b70 (HEAD ->
> nimmo-update-rails-gems-6.1.7.6, origin/nimmo-update-rails-gems-6.1.7.6)
> Author: andrew nimmo ***@***.***>
> Date:   Thu Aug 31 15:49:36 2023 -0700
>     Change references to MiniTest -> Minitest
> $ bundle install
> Fetching gem metadata from https://rubygems.org/.........
> ...
> Fetching psych 5.1.0
> ...
> Installing psych 5.1.0 with native extensions
> ...
> Using sassc-rails 2.1.2
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
>
>
>     current directory:
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/psych-5.1.0/ext/psych
> /home/vagrant/.rbenv/versions/3.1.2/bin/ruby -I
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0 -r
> ./siteconf20230831-2547-hq6n7a.rb extconf.rb
> checking for yaml.h... no
> yaml.h not found
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You
> may
> need configuration options.


> Provided configuration options:
>         --with-opt-dir
>         --without-opt-dir
>         --with-opt-include
>         --without-opt-include=${opt-dir}/include
>         --with-opt-lib
>         --without-opt-lib=${opt-dir}/lib
>         --with-make-prog
>         --without-make-prog
>         --srcdir=.
>         --curdir
>         --ruby=/home/vagrant/.rbenv/versions/3.1.2/bin/$(RUBY_BASE_NAME)
>         --with-libyaml-source-dir
>         --without-libyaml-source-dir
>         --with-yaml-0.1-dir
>         --without-yaml-0.1-dir
>         --with-yaml-0.1-include
>         --without-yaml-0.1-include=${yaml-0.1-dir}/include
>         --with-yaml-0.1-lib
>         --without-yaml-0.1-lib=${yaml-0.1-dir}/lib
>         --with-yaml-0.1-config
>         --without-yaml-0.1-config
>         --with-pkg-config
>         --without-pkg-config
>         --with-libyaml-dir
>         --without-libyaml-dir

        --with-libyaml-include
>         --without-libyaml-include=${libyaml-dir}/include
>         --with-libyaml-lib
>         --without-libyaml-lib=${libyaml-dir}/lib


> To see why this extension failed to compile, please check the mkmf.log
> which can be found here:
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/psych-5.1.0/mkmf.log
> extconf failed, exit code 1
> Gem files will remain installed in
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/psych-5.1.0
> for inspection.
> Results logged to
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/psych-5.1.0/gem_make.out
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in
> `run'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in
> `block in build'
>   /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tempfile.rb:317:in
> `open'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in
> `build'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in
> `build_extension'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in
> `block in build_extensions'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in
> `each'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in
> `build_extensions'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/installer.rb:853:in
> `build_extensions'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:71:in
> `build_extensions'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:28:in
> `install'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/source/rubygems.rb:204:in
> `install'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:54:in
> `install'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:16:in
> `install_from_spec'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:186:in
> `do_install'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:177:in
> `block in worker_pool'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:62:in
> `apply_func'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:57:in
> `block in process_queue'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in
> `loop'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in
> `process_queue'
>
> /home/vagrant/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.15/lib/bundler/worker.rb:91:in
> `block (2 levels) in create_threads'


> An error occurred while installing psych (5.1.0), and Bundler cannot
> continue.


> In Gemfile:
>   debug was resolved to 1.8.0, which depends on
>     irb was resolved to 1.8.0, which depends on
>       rdoc was resolved to 6.5.0, which depends on
>         psych
> $

**Comment by nimmolo** [comment]
@JoeCohen 
Did you run these two before restarting Vagrant?
```
vagrant@ubuntu-focal:/vagrant/mushroom-observer$ sudo snap install port
vagrant@ubuntu-focal:/vagrant/mushroom-observer$ port install libyaml +universal
```

**Comment by JoeCohen** [comment]
No, I did not. I wanted to see if it would work without that.
If I need to do that on the vm, then would we also need to do it on the
webserver? (Or is it only a Vagrant issue?) Would we need to update
developer_startup?

**Comment by nimmolo** [comment]
I think it's a vagrant box issue. Not entirely current with Focal. On Aug 31, 2023, at 6:16 PM, Joseph D. Cohen ***@***.***> wrote:﻿
No, I did not. I wanted to see if it would work without that.

If I need to do that on the vm, then would we also need to do it on the

webserver? (Or is it only a Vagrant issue?) Would we need to update

developer_startup?



On Thu, Aug 31, 2023 at 5:42 PM andrew nimmo ***@***.***>

wrote:

**Comment by JoeCohen** [comment]
Thanks. I'll give it a try.

**Comment by nimmolo** [comment]
Now that i think about it, you're right. We might need to update production. 
And it would be nice to update the Vagrant box, to keep it in sync, if this works for you. 
I've downloaded the base box.

**Comment by JoeCohen** [comment]
Tried it but getting hung up where I think you were hung up:

***@***.****:*~*$ port install libyaml +universal

/snap/port/78/port/port: /lib/x86_64-linux-gnu/libc.so.6: version
`GLIBC_2.30' not found (required by
/snap/port/78/usr/lib/x86_64-linux-gnu/libnspr4.so)

/snap/port/78/port/port: /lib/x86_64-linux-gnu/libm.so.6: version
`GLIBC_2.29' not found (required by
/snap/port/78/usr/lib/x86_64-linux-gnu/libasound.so.2)

***@***.****:*~*$
I've updated both VirtualBox (Version 7.0.10 r158379 (Qt5.15.2))
and Vagrant (2.3.7).

Any suggestions?

**Comment by nimmolo** [comment]
Yes. When i got to that point, i tried 360 ways to install that version of glibc-2.30, and it is not available.

Then i just halted and reloaded vagrant, and everything worked.

**Comment by JoeCohen** [comment]
Thanks Nimmo. I think I tried that.
Exactly how did you do that?
In any event, I'll try again tomorrow; it's getting too late for me to
think clearly about that.

**Comment by nimmolo** [comment]
@JoeCohen I think i've got it. 
Lock the `gem("psych", "~>4")` and it bundles.

**Comment by JoeCohen** [comment]
Thanks again! I will try it tomorrow. Once again, today got away from me.

**Comment by nimmolo** [comment]
@JoeCohen can you confirm this loads and bundles for you without any further modification?

**Comment by JoeCohen** [comment]
I'm working on it now. I had to destroy my VM.
I'll get back to you shortly.

**Comment by nimmolo** [comment]
Oh no. Sorry to hear that. 

Well, the Jammy box I made yesterday is working well, seems actually a bit quicker. I can send you an updated Vagrantfile if you want to try it.

**Comment by nimmolo** [comment]
OH! Also note that the Vagrantfile on developer-startup had a typo until yesterday. I fixed the typo, so if you’re building a new box be sure you update Vagrantfile from dev-startup before you do. (I’d still recommend the built Jammy box)

**Comment by JoeCohen** [comment]
I think the rebuilt mo-focal-2022-12-21 is working fine.
I'm just waiting for the test suite to finish. ETA 1:10.

**Comment by JoeCohen** [comment]
Tests all pass. I think you should merge. (Or I can do that if you like.)
Thanks again for digging into this and finding the fix.

**Comment by nimmolo** [comment]
Thanks Joe!

**Pull request merged**
