### PR TITLE
Rubocop 1.31

### PR DESCRIPTION
**Pull request by JoeCohen**
This PR upgrades to Rubocop 1.31.1:
- update the Codeclimate Rubocop channel to the highest available version (1.31.0)
- explicitly enable/disable cops that were added in Rubocop 1.31.1
- fix offenses of newly enabled cops
- update .rubocop
- change comments in .rubocop.yml

### CODE REVIEW

**Comment by JoeCohen** [comment]
Review IFF you feel like it, 
or if you want something especially boring to fill time.
The changes are sufficiently trivial so I'll probably merge it soon.

**Comment by nimmolo** [comment]
@JoeCohen Did codeclimate suddenly raise their support of Rubocop versions? Wasn't it stuck in at 1.23 for awhile?
In any case, glad you have this moving. I will definitely need to Zoom with you again to get my rubocop, rvm, etc working locally!!

**Review by nimmolo — APPROVED** [review]

**Comment by JoeCohen** [comment]
@nimmolo Codeclimate did update their support to Rubocop 1.30.0, and then -- to my surprise -- to 1.31.0.
Let's figure out a time to Zoom. I'll email you.

**Comment by pellaea** [comment]
Go ahead without me, I'm swamped.

**Pull request merged**
