### PR TITLE
Hash lookup for Inat::Obs attributes

### PR DESCRIPTION
**Pull request by JoeCohen**
- Uses hash lookup to access `Inat::Obs` attributes.
- Removes needless, repetitive pattern of defined methods.
Ex: `inat_obs[:id]` instead of `inat_obs.inat_id`
- Fixes `Inat::Obs` class length metric offense.
- Responds to [@mo-nathan suggestion](https://github.com/MushroomObserver/mushroom-observer/pull/2150#discussion_r1762039634).
- Replaces #2416 

There is no manual test.

### CODE REVIEW

**Comment by nimmolo** [comment]
Joe - I believe there is a better, more standard Railsy way to do all this, and there's an example on my PR:

Define your inat_obs as an activemodel object. This gives you the accessor methods without repetitive declarations, and other goodies besides. You won't have to access by hash key. 

It's a "model not backed by a db table" and it's a very convenient thing.

**Comment by JoeCohen** [comment]
Thanks! Which pr has an example?

**Comment by nimmolo** [comment]
#2337 — which as of yesterday does not require any migrations to check out, so it won't mess up your local db!

**Comment by JoeCohen** [comment]
@nimmolo: TLDR: I like the idea of a model not backed by a db table, but will postpone it till after NEMF.

1. I want a good window, before NEMF, for live shakedown tests of iNat import.
2. What I have now works, so I'd prefer to postpone refactors until after NEMF.
3. The hash stuff is convenient because it differentiates the raw iNat data from methods which manipulates or map that data. But that might indicate that Inat::Obs has too many concerns, and therefore that I should create another class. That's something that I certainly don't want to attempt prior to NEMF.
4. The hash stuff also works with all levels of the iNat data. I don't know about a model not backed by a db table, and don't want to take time right now find an answer.

> Joe - I believe there is a better, more standard Railsy way to do all this, and there's an example on my PR:
> 
> Define your `inat_obs` as an `ActiveModel::Model` object, rather than a bare PORO.
> 
> This gives you the accessor methods without repetitive declarations, and potentially other goodies besides, like validation (although i didn't use that). You won't have to access your attributes by hash key. It makes it work like a model instance (because it is).
> 
> It's a "model not backed by a db table" and it's a [very convenient thing](https://testdouble.com/insights/rails-forms-non-active-record-objects). This is what people do for form data where the are assembling attributes that may go into some other model (like an `observation`, in your case) but they want the attributes of the form accessible like a model, too.
> 
> I've known about this for years but never understand quite how to use it, but now that I did, I realize how easy it is and will be using it elsewhere.
> 
> Check ObservationFilter at `app/models/observation_filter.rb` and NameFilter, which are based on a model SearchFilter that inherits from ActiveModel. It's at `app/models/search_filter.rb`.
> 
> ```ruby
> class SearchFilter
>   include ActiveModel::Model
>   include ActiveModel::Attributes
> 
>   attribute :pattern, :string
> ```

**Pull request merged**
