### PR TITLE
Herbarium form modal (reusable Location-creation UI)

### PR DESCRIPTION
**Pull request by nimmolo**
- Generalize the "create Location" UI from the observation form so it can be used to create a location within any form that has location autocompletion. Trying it here on Fungarium first, because it's minor, so we can work out the bugs.
- Develop reusable Turbo methods to update the state of _one form_ when _another form_ is submitted. In this case, on successful creation of a Fungarium, Turbo populates the `herbarium_record_herbarium_name` and `herbarium_record_herbarium_id` fields of the create obs form **from the Rails controller response, without writing JS** (other than the reusable Turbo methods)
- Make the seldom-used "Create fungarium" link (in create obs) open a modal form, so it can be filled out right on the create obs page without interrupting flow. (I'm not sure how many people suddenly want to create a Fungarium when they're in the middle of recording an Observation... but that's what we offer)
- This is a test run for creating Locations from within the "Create Project" and "User Profile" forms

Screen Shot 2024-08-06 at 11 32 11 AM

- Note here that the Fungarium form also must offer to "create a new Locality" in case your specimens are in a place we don't have. I considered yet another modal, but then settled upon generalizing the create-location UI. This PR adds the map/create-location UX to the Location autocompleter.

Screen Shot 2024-08-06 at 11 29 42 AM

- [x] TODO: revert to MO Location autocompleter if "create" form text is blanked. 
- [x] TODO: handle new location in Herbaria controller new/edit actions
- [x] TODO: system tests for the forms
  - [x] Regular herbarium new/edit, test that `location` is created when form submitted
  - [x] Observation new/edit, test that `herbarium` and `location` are created, and herbarium applied to observation `herbarium_record`

Successfully creating a Fungarium in the modal form now populates that new fungarium in the Observation form, and allows you to continue creating the obs.

Background: on the observation form, the "Create fungarium" link kind of interrupts the flow of creating an obs.

Screen Shot 2024-08-03 at 3 07 37 PM

### CODE REVIEW

**Comment by nimmolo** [comment]
Please take a minute to test this manually at two places:
- `herbaria/new` the usual place for creating a fungarium. The thing that needs testing is creating a new Location during the process of filling out the form.
- `observations/new`. If you click "has_specimen" you should see a link to "create fungarium" above the name of your default fungarium. This will open a pop-up modal form just like the above, where you should be able to 
  - create a new location for a fungarium
  - create the fungarium
  - find the brand new fungarium filled in on the create obs form.

**Comment by JoeCohen** [comment]
Very slick. Picks up lots of stuff automatically.
But it seems to get stuck in the Create New Fungarium modal when trying to Create Locality while creating new Herbarium while creating an Obs. What I did:
- Create Observation
- Drag 2 photos (Love how this works with automatically getting the date & location.
- Folded Images + Details.
- In Identification + Specimen::
  - Filled in Scientific Name, selected Confidence, checked Specimen Available.
  - Clicked Create New Fungarium. (I didn't fill in Collector's Number, Accession Number or Fungarium Record Notes.)
Result: Opened Create New Fungarium modal. In that modal:
    - Filled in Name 
    - Did NOT check personal fungarium box.
    - In Location, typed non-existent Location (`McMinnville, Yamhill Co., Oregon, USA`) 
    Result: `Create locality` button appears. NIce! (Do you want to capitalize "locality"?)
    - Clicked `Create locality`
    Result: Map appears with correct bounding box. Create locality match found check icon appears. 
    - Clicked `Create` button.
    Result: **No visible change**. (But Location was created behind the scenes without notifying user.)
    What should I do now? **I'm apparently stuck in the Create New Fungarium modal, with no way out.** 

Screenshot 2024-08-24 at 4 59 51 AM
If I close the modal, click Create New Fungarium, I'm back to the modal, where click Create does nothing.

**Comment by nimmolo** [comment]
Joe,
I heard about all that mushroom rustling up in McMinnville, and I put two and two together, and, well... this was the only way I knew to bring the suspect to justice. 

I'm afraid you'll have to wait here in the modal until the sheriff comes.

**Comment by nimmolo** [comment]
Thanks Joe for all the feedback. I’m just trying out the flow you did, and i get a different result, when i click “Create” on the fungarium modal:
- A flash in the create obs form, with three success messages 
screen_shot_2024-08-24_at_12 35 03_pm
- The new fungarium name now filled out in the form. (It should probably remove the “Create” button at this point, I’m realizing.)
screen_shot_2024-08-24_at_12 35 53_pm

**Comment by mo-nathan** [comment]
I spent a while on the Create Fungarium stuff inside the Create Observation stuff and my assessment is that it isn’t worth it.  The use case I spent the most time on was creating an observation that I want to deposit at the MBLWHOI Library Herbarium (see https://mblwhoilibrary.org/special-collections/mblwhoi-library-herbarium/).  The first issue I ran into is that it isn’t clear from the Create Observation UI whether the fungarium/herbarium even exists when I enter the name for it.  Given that it doesn’t seem worth adding to the Create Observation workflow.  Creating a fungarium should be a rare event.  I don’t see the justification for making it really easy to do from the UI.  Out of the 7477 herbaria in the system, only 1629 have any associated observations, and only 746 have more than one.  Beyond that, the embedded location creation UI seems to be wonky.  I can create this herbarium through the Create Fungaria UI and I can create the location itself through the create location UI.  It’s only when it’s embedded in the Create Observation UI that it gets weird.  I did a screen capture showing the weirdness and uploaded it through Slack since it's too big for GitHub.

**Comment by nimmolo** [comment]
Going to go ahead and merge this.

**Pull request merged**
