### PR TITLE
Glossary Guidelines

### PR DESCRIPTION
**Pull request by JoeCohen**
Adds a `.md` file to the repo with detailed documentation of Glossary Term guidelines.

This is the first (and largest) step in https://www.pivotaltracker.com/n/projects/224629.
It must precede the other steps in order to have a stable link to the document.

Includes accompanying visuals.

There is no manual test.

### CODE REVIEW

**Comment by JoeCohen** [comment]
This documentation seems way too long (and complex) to do (and modify) in the form "translated" symbol.
In the past, I've created similar long and complex documentation as Google Docs (owned by webmaster).
Example: [Names in Mushroom Observer](https://docs.google.com/document/d/1xOEIAGzb2NoGfeC1QMvVmwtWK-gYyZqKkt7yKv61WY0/edit?usp=drive_link)

This time I decided to try a `.md` that lives in the repo.

**Comment by JoeCohen** [comment]
My plan is to link to the file in the repo (as opposed to in the website). 
Therefore I need to merge this PR so that I can get stable links to the file.
I may take the liberty of merging this PR without waiting for comments. 
(We can change the file later without affecting those links.)

**Comment by pellaea** [comment]
Works for me.  I appreciate the work, Joe!  I'm unable to load the google
doc (that's not unusual for my internet connection), but I trust you!

**Comment by JoeCohen** [comment]
I appreciate the feedback.

**Comment by JoeCohen** [comment]
Merging this because:
- It's blocking other stuff;
- It's "just" documentation, so can easily be adjusted without affecting any functionality.

**Pull request merged**
