### PR TITLE
Show obs: Move edit, destroy, manage species list links to panels

### PR DESCRIPTION
**Pull request by nimmolo**
Screen Shot 2024-02-06 at 12 54 57 PM

### CODE REVIEW

**Comment by nimmolo** [comment]
@JoeCohen - Does this work for you? 
 - For "edit", i feel like "Details" is the right place. If you're editing an obs, it's a logical place to look.
 - For "destroy", it's maybe not so obvious, but it makes sense to have it next to "edit"
 - They both have hover "tooltips" (labels)

When I get the observation's "title bar" reorganized (including the "interest eyes"), I'd maybe like to put the edit/destroy links in that title bar. But we're not there yet.

**Comment by JoeCohen** [comment]
The layout works for me.
(I haven't had a chance to drive it because I haven't updated my local environment to match the recent db changes.)

**Comment by mo-nathan** [comment]
Sorry I don't really understand what the change was here.

**Comment by nimmolo** [comment]
@mo-nathan The change was moving three links from being text 'tab' links in the top right corner of the page, to the icons shown in the screen grab in the first comment:

Edit Observation  (moved to the Details section)
Destroy Observation  (moved to the Details section)
Manage Species Lists   (moved to the Species Lists section. This section was previously not shown before if the obs was not part of any species lists)

**Comment by mo-nathan** [comment]
Ok, got it.  Thanks!

**Pull request merged**
