### PR TITLE
Refactor Lookups Controller

### PR DESCRIPTION
**Pull request by JoeCohen**
- Reduces AbcSize of `LookupsController#lookups_general` from 82.13 to <= 17 (the current default).
- Fixes other RuboCop offenses in the controller.

### CODE REVIEW

**Comment by JoeCohen** [comment]
@nimmolo, @jason
I'd like to merge this in the next day or two unless there are objections.

**Comment by nimmolo** [comment]
Thanks Joe. I'm not sure I entirely get what's going on in this controller, but the refactor seems good fwiw. 

I'm guessing it has to do with links to objects within Textile such as comments and descriptions, and not instantiating the referred objects.

**Comment by JoeCohen** [comment]
Nimmo:
Thanks for the feedback. You are correct.
It also allows external links that are independent of the object id. (The
object id can change, at least for Names and Locations, at least in the
event of merger.)
- Joe

**Comment by pellaea** [comment]
This looks good to me, too.  Thanks for cleaning it up, Joe.

**Pull request merged**
