### PR TITLE
Fix project and species list forms and redirects after commit

### PR DESCRIPTION
**Pull request by nimmolo**
This changes "add member to project/change_member_status" and "add/remove observation to species list" forms to redirect to the relevant project or species list after commit.

These (to me) intuitively feel like the most constructive redirects, but i don't use these features, please let me know if this should be different. Nothing better than a test drive, probably.

It also adds a new "remove" button to each obs in the list of observations of a species list. When playing with the interface, I felt like it needed one.

### CODE REVIEW

**Review by JoeCohen — COMMENTED** [review]
Thanks for all the fast fixes. This looks great.
I'd like to take the opportunity to cover `/app/controllers/observations/species_lists_controller.rb` lines 44-45. 
I can do that after 3:00pm. 
But if you want to merge it now, that's also fine. (Those lines weren't covered before.)

**Comment by JoeCohen** [comment]
Thanks for the feedback.
I have to join my meeting in 2 minutes. I'll work on the test starting
around 3pm

**Comment by nimmolo** [comment]
@JoeCohen - did you mean to delete this branch? It's not merged...

**Comment by JoeCohen** [comment]
OH NO

**Comment by JoeCohen** [comment]
Thanks! I was trying to delete it locally. 
Something went wrong in VScode.

**Pull request merged**
